aws-greengrass/aws-greengrass-client-device-auth

pom.xml
src/main/java/com/aws/greengrass/certificatemanager/CertificateManager.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/CISShadowMonitor.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitor.java
src/test/java/com/aws/greengrass/certificatemanager/CertificateManagerTest.java

Deduplicates server certificate subscriptions based on the pair of csr and callback. Also implements the unsubscribe method in order to remove the subscription.

fix(cert-sub): deduplicate server certificate callbacks

---

pom.xml
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/test/java/com/aws/greengrass/device/ClientDevicesAuthServiceTest.java

Currently we subscribe to `ca_type` and `deviceGroups` separately.
When we reset the configuration using `[""]`, we lose the subscription in the process.
Subscribing to `configuration` allows us to preserve the subscription.
When we reset the configuration for `deviceGroups` using `[""]`, we lose the subscription in the process.
Any further updates to the config are not parsed by CDA
`mvn clean verify`
Currently there are 2 tests that are failing.
One of those tests (ClientDevicesAuthServiceTest.GIVEN_GG_with_cda_WHEN_updated_ca_type_THEN_ca_is_updated) passes when run independently but fails when …

fix: subscribe to configuration topic instead of child topics

---

src/main/java/com/aws/greengrass/certificatemanager/CertificateManager.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateGenerator.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfig.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/ClientCertificateGenerator.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/ServerCertificateGenerator.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/test/java/com/aws/greengrass/certificatemanager/CertificateManagerTest.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitorTest.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfigTest.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/ClientCertificateGeneratorTest.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/ServerCertificateGeneratorTest.java
src/test/java/com/aws/greengrass/device/DeviceAuthClientTest.java

This change adds a CertificatesConfiguration class for managing configuration related to certificate generation. Refactoring was required in order to plumb this all the way through.
This change also introduces a `serverCertificateValiditySeconds` configuration for controlling how long server certificates are valid for. Currently this value is only configurable up to 10 days. We can increase this further after consulting with AppSec.
We have industrial customers who cannot tolerate MQTT broker restarts outside of scheduled maintenance windows. This change is needed in order so that customers can manually restart the MQTT broker once a week to retrieve a new certificate and avoid automatic rotation. …

feat: introduce serverCertificateValiditySeconds config

---

src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfig.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfigTest.java

This change introduces a clientCertificateValiditySeconds configuration for
controlling how long client certificates are valid for. Currently this value is only
configurable up to 10 days.

feat: introduce clientCertificateValiditySeconds config

---

src/main/java/com/aws/greengrass/certificatemanager/certificate/ClientCertificateGenerator.java

Add logging when client certificates are rotated to aid in debugging

fix: add logging when rotating client certificates

---

src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitor.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitorTest.java

Remove timeouts and use of ScheduledExecutorService. Replace it with mock 
Fix indeterministic behavior of the tests
`mvn clean verify`

test: fix CertificateExpiryMonitorTests to not use ses

---

pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/SubscribeToCertificateUpdatesTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/BrokerNotAuthorized.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/cda.yaml
src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateHelper.java
src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateStore.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/ipc/SubscribeToCertificateUpdatesOperationHandler.java
src/test/java/com/aws/greengrass/device/ClientDevicesAuthServiceTest.java

This change registers the CDA component and possible operations it exposes with IPC. IPC agent for CDA is added to send server certificate update events to the components as a streaming response. 
We're exposing server certificate updates (both generation and rotation) over IPC to facilitate any authorized non-plugin component (such as new MQTT 5 broker or BYOB) to subscribe to its certificate updates from the CDA component. 
Flow:
1. An Mqtt broker server subscribes to its certificate updates over IPC using streaming response handler. The subscribe request consists of the following. 
``` …
```

feat: add IPC agent and expose cert updates over IPC

---

src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/device/DeviceAuthClient.java
src/main/java/com/aws/greengrass/device/SessionManager.java
src/main/java/com/aws/greengrass/device/configuration/ExpressionVisitor.java
src/main/java/com/aws/greengrass/device/configuration/GroupDefinition.java
src/main/java/com/aws/greengrass/device/configuration/GroupManager.java
src/main/java/com/aws/greengrass/device/iot/Certificate.java
src/main/java/com/aws/greengrass/device/session/AbstractSessionFactory.java
src/main/java/com/aws/greengrass/device/session/MqttSessionFactory.java
src/main/java/com/aws/greengrass/device/session/Session.java
src/main/java/com/aws/greengrass/device/session/SessionCreator.java
src/main/java/com/aws/greengrass/device/session/SessionFactory.java
src/main/java/com/aws/greengrass/device/session/SessionImpl.java
src/main/java/com/aws/greengrass/device/session/SessionManager.java
src/test/java/com/aws/greengrass/device/DeviceAuthClientTest.java
src/test/java/com/aws/greengrass/device/SessionManagerTest.java
src/test/java/com/aws/greengrass/device/configuration/GroupDefinitionTest.java
src/test/java/com/aws/greengrass/device/configuration/GroupManagerTest.java
src/test/java/com/aws/greengrass/device/configuration/parser/RuleExpressionEvaluationTest.java
src/test/java/com/aws/greengrass/device/session/AbstractSessionFactoryTest.java
src/test/java/com/aws/greengrass/device/session/MqttSessionFactoryTest.java
src/test/java/com/aws/greengrass/device/session/SessionCreatorTest.java
src/test/java/com/aws/greengrass/device/session/SessionImplTest.java
src/test/java/com/aws/greengrass/device/session/SessionManagerTest.java

Adds basic session management code for creating sessions based on device credentials as opposed to certificates. It introduces a `SessionCreator` which can be used to instantiate sessions based on credentials of differing types, as well as a factory for creating based on MQTT credentials.
This also removes some unused code and adds unit tests.
This change is needed in order to create sessions based on MQTT device credentials.
Unit testing. Manually tested integration with Moquette
This change is functional, but not complete. There are a couple of TODOs in the code that need to be addressed still: …

feat: support for mqtt device credentials

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/ipc/VerifyClientDeviceIdentityOperationHandler.java

Exposes verifying client device identity over IPC. 
Facilitate any authorized non-plugin component (such as new MQTT 5 broker or BYOB) to verify client device identity over IPC.
Added integ tests. 

feat: expose verifying client device identity over ipc

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/AuthorizeClientDeviceActionTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/BrokerNotAuthorized.yaml
src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/cda.yaml
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/device/DeviceAuthClient.java
src/main/java/com/aws/greengrass/device/exception/AuthenticationException.java
src/main/java/com/aws/greengrass/device/exception/AuthorizationException.java
src/main/java/com/aws/greengrass/device/exception/CloudServiceInteractionException.java
src/main/java/com/aws/greengrass/device/exception/InvalidSessionException.java
src/main/java/com/aws/greengrass/ipc/AuthorizeClientDeviceActionOperationHandler.java

This change exposes authorizing client device action over IPC. Returns either True or False if a valid session exists and is able to authorize certain operation on a resource. 
If a valid session is not found, then `InvalidClientDeviceAuthTokenError` is thrown. 
For all other exceptions, `ServiceError` is thrown.
Needed for mqtt5/byob  integration. 
Added integrations tests. 

feat: expose authz client device action over IPC

---

src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/ipc/VerifyClientDeviceIdentityOperationHandler.java

Depends on https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/1213
This PR requires an additional change to the OperationContinuationHandler in Nucleus in order to test fully successfully.
This change is the first step in changing VerifyClientDeviceIdentity to be asynchronous. It uses its own threadpool which has a limited thread count and queue size (1 and 100 respectively right now). It is only the first step because we will need to make the threadpool more configurable in addition to some cleanup logic and potentially caching.
All tests ran and passed on my mac with the required Nucleus change.
```
[INFO] Results:
[INFO]
[INFO] Tests run: 160, Failures: 0, …
```

fix: begin VerifyClientDeviceIdentity conversion to async

---

src/main/java/com/aws/greengrass/certificatemanager/certificate/CISShadowMonitor.java
src/main/java/com/aws/greengrass/cisclient/ConnectivityInfoProvider.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CISShadowMonitorTest.java

This change fixes the handling of CIS shadow delta updates within `CISShadowMonitor` and adds more exception logging:
* `UpdateShadowRequest#state` field is now populated. Previously, this was causing a `NullPointerException` when the request was processed by `IotShadowClient`.
* `lastVersion` is **always** set after certs have been rotated, to prevent unnecessary cert rotations if the same shadow delta version is processed twice.
* All exceptions are now logged via `CompletableFuture#exceptionally`, when previously some were silently ignored.
* `CISShadowMonitorTest` is completely refactored and uses a fake implementation of `IotShadowClient`.  This allows the test to hit the `NullPointerException` code path mentioned above.
**Why is …

fix: add state to update shadow request

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/main/java/com/aws/greengrass/ipc/VerifyClientDeviceIdentityOperationHandler.java

EMQ X gives us the PEM as just the base64 bytes, without any certificate header or line wrapping. This change will check for that case and re-encode the certificate in the required format.

fix: re-encode certificate for lookup as needed

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/ipc/GetClientDeviceAuthTokenOperationHandler.java
src/main/java/com/aws/greengrass/util/ResizableLinkedBlockingQueue.java

- make GetClientDeviceAuthToken IPC API asynchronous
- make the async threadpool configurable by users in terms of the number of threads and the queue size
Existing tests passing, added test case for when the queue is full that the request is rejected appropriately.

feat: implement async IPC for GetClientDeviceAuthToken, make settings configurable

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
src/main/java/com/aws/greengrass/ipc/GetClientDeviceAuthTokenOperationHandler.java
src/main/java/com/aws/greengrass/ipc/IPCUtils.java
src/main/java/com/aws/greengrass/ipc/VerifyClientDeviceIdentityOperationHandler.java

Re-encode certificate PEM of the `GetClientDeviceAuthTokenRequest` IPC request if it is not encoded already. 
Same as https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/81

fix: re-encode cert of the GetClientDeviceAuthTokenRequest

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/device/DeviceAuthClient.java
src/main/java/com/aws/greengrass/device/iot/Component.java
src/main/java/com/aws/greengrass/device/session/MqttSessionFactory.java
src/main/java/com/aws/greengrass/ipc/VerifyClientDeviceIdentityOperationHandler.java
src/test/java/com/aws/greengrass/device/DeviceAuthClientTest.java
src/test/java/com/aws/greengrass/device/session/MqttSessionFactoryTest.java

Handle certificates coming from internal components (ie. Bridge).

fix: create session for internal components via new SessionManager

---

src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfig.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfigTest.java

Removes the `clientCertificateValiditySeconds` config
We are not releasing this, so it should be removed

revert: configurable client cert rotation period

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/device/session/SessionConfig.java
src/test/java/com/aws/greengrass/device/session/SessionConfigTest.java

**Description of changes:** 
- rename and namespace `sessionCapacity` config to `configuration.performance.maxActiveAuthTokens`
- update `sessionCapacity` default to 2500
- clamp invalid configured `sessionCapacity` values to the valid range instead of default
- rename `cloudQueueSize` -> `cloudRequestQueueSize` , `threadPoolSize` -> `maxConcurrentCloudRequests`
- namespace `cloudRequestQueueSize` and `maxConcurrentCloudRequests` config under `configuration.performance`
New CDA config:
```
|---- configuration
|    |---- performance:
|         |---- cloudRequestQueueSize: "..."
|         |---- maxConcurrentCloudRequests: "..."
|         |---- maxActiveAuthTokens: "..."
|    |---- deviceGroups:
|         |---- definitions : {}
|         |---- policies : {}
|    |---- ca_type: [...]
| …
```

fix: rename and namespace sessionCapacity config

---

src/main/java/com/aws/greengrass/device/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/device/ClientDevicesAuthServiceApi.java
src/main/java/com/aws/greengrass/ipc/AuthorizeClientDeviceActionOperationHandler.java
src/main/java/com/aws/greengrass/ipc/GetClientDeviceAuthTokenOperationHandler.java
src/main/java/com/aws/greengrass/ipc/VerifyClientDeviceIdentityOperationHandler.java

Move IPC API functionality into ClientDevicesAuthServiceApi class so that it can also be used directly by internal clients.
This change also removes external dependence on the DeviceAuthClient, which will allow us to remove some of that dead code in a subsequent PR.
This change is needed in simplify Moquette changes needed to handle session eviction. Specifically, this enables Moquette to create sessions in one shot, rather than creating a session based on client certificate and then attaching thing information.
Unit / integ tests. Manual tests with updated Moquette.
Corresponding Moquette change: …

refactor: move IPC APIs to ClientDevicesAuthServiceAPI

---

src/main/java/com/aws/greengrass/device/ClientDevicesAuthServiceApi.java

Re-add closeClientDeviceAuthSession API to opportunistically close sessions even though it's not required

feat: add closeClientDeviceAuthSession to API wrapper

---

src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateRequestGenerator.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateHelperTest.java
src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateRequestGeneratorTest.java

Properly constructs the X500 Principal which is used as the Subject in generated certificates.
This change also removes some code that is no longer needed.
Manual testing to ensure OpenSSL can parse the subject in broker server certs

fix: cert gen fixes

---

src/main/java/com/aws/greengrass/clientdevices/auth/DeviceAuthClient.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/SessionManager.java
src/test/java/com/aws/greengrass/clientdevices/auth/DeviceAuthClientTest.java

Removes unused code in the DeviceAuthClient and in SessionManager. With
this change, there is no longer a way to create an auth session without
a complete set of device credentials. This will enable us to do things
like add session de-dup logic in the future

chore!: remove unused session creation code

---

src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/test/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthServiceTest.java

When uploading the core CA to cloud fails, CDA retries for certain type of exceptions like `ThrottlingException` and `InternalServerException` where as for all other exceptions, the service goes into error state. 
But with this change, for all other non-retryable exceptions, we log the exception but do not put the service in error state. We retry for `AccessDeniedException` as well.  
When we support offline authentication, client devices do not get the core device CAs from the cloud. So, even when the core device fails to upload the core CAs to cloud, client device auth component should be running as the client devices do not rely on them in all the cases. 
Updated …

fix: do not throw an error when cloud upload fails

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/CertificateRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistry.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/CertificateRegistryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistryTest.java

**Description of changes:** CertificateRegistry returns locally registered results when cloud is unreachable.
**Why is this change necessary:** required for enabling offline auth
**How was this change tested:** unit tests, integ tests

feat: enable offline certificate registry access

---

pom.xml
src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfiguration.java
src/main/java/com/aws/greengrass/clientdevices/auth/exception/InvalidCertificateAuthorityException.java
src/main/java/com/aws/greengrass/clientdevices/auth/exception/InvalidConfigurationException.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfigurationTest.java

This PR adds support for configuring custom certificates from the provided `certificateAuthority` configuration.
This introduces the ability for customers to provide their own CA instead of having the CDA generate it.
There are 2 new tests that ensure the appropriate certificate chain is set once it is provided.

feat: support configurable CA

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/AuthorizeClientDeviceActionTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/SubscribeToCertificateUpdatesTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureCertificateAuthorityUseCase.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/RegisterCertificateAuthorityUseCase.java
src/test/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthServiceTest.java

Splits CA upload into a separate use case so that it can be independently retried. For now this use case is called from within the original configure CA use case, but eventually it may be called independently (for example, if the network is down when we start).
Additionally, this also uses the new Nucleus API for retrieving the data client. This new API throws a checked exception for invalid DeviceConfiguration rather than an NPE, which will allow us to do something more intelligent later.
Unit tests.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

refactor: split upload CA into separate use case

---

src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/api/UseCases.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureCertificateAuthorityUseCase.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/CDAConfiguration.java
src/test/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthServiceTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/UseCasesTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/usecases/ConnectivityInformationUseCasesTest.java

Ensure we are calling the use case to configure the certificate authority every time there is a change on the CDA configuration for the `certificateAuthority`.
Additional changes:
* Made the UseCases injectable instead of a singleton due to the fact it make them easier to test by allowing us to mock provided values of use cases in case we want to do simple unit tests.
We need to make sure we are updating the CAs when any value under the certificateAuthority configuration changes
Wrote a unit test.

feat: call configure ca every time the certificateAuthority config changes

---

src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java

This change adds support for returning the entire CA certificate chain to clients who subscribe to certificate updates. This change is required in order to support Greengrass using an intermediate CA to issue server certificates.
Unit tests. Manually testing with MQTT broker to ensure that the full certificate chain is returned as part of the SubscribeToCertificateUpdates operations.

fix: present full cert chain

---

src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java

Stop injecting everything into CDA and just grab it from the context when it's needed.
More of this will eventually go away once we introduce more UseCases. Infrastructure init will also move, along with configuration.
It's not. Just cleans things up a bit.

refactor: simplify CDA service entry

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/certificateauthority/config.yaml
src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/api/Result.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/RegisterCertificateAuthorityUseCase.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java

This CR changes what CA is uploaded to Iot core so that validation of client devices work when providing a certificate chain. Customers having clients using V1 of the IoT device SDK must provide the full certificate chain to CDA in order to be successfully authenticated. V2 is a bit more lenient, it allow clients to be validated with partial chains (meaning not having a core CA present and using and intermediate as a Trust anchor) 
We need this change so that customers bringing their own CA with clients on V1 of the SDK can continue to successfully authenticate their devices using the CA returned from cloud discovery.
Manually tested and validate that authentication would work using openssl by …

feat: upload the ca with the highest trust level from the ca chain

---

src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/ClientCertificateGenerator.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/ServerCertificateGenerator.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateExpiryMonitorTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/ClientCertificateGeneratorTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/ServerCertificateGeneratorTest.java

Fix issue where old CA's are getting returned if the ca chain changes
This is part of a larger fix to ensure that we are rotating the certificates when the CA configuration changes.  It is required so that client components get the latest CA values and can properly authenticate.
Wrote a test

Ensure latest CA are returned to subscribers when they change

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CAConfigurationMonitor.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java

This add a mechanism for us to trigger the subscriber when the ca changes
Without this change, changing the configuration does not rotate the certificates, causing component to fail authentication
Check and run the integration tests

feat: rotate certificates when ca changes

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CAConfigurationMonitor.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java

Update caChain and private key together to avoid leaving the door open for someone to update the caChain without changing the private key which would lead to generating invalid certificates.
If we don't do this, depending on how we hook the events it can happen that we generate certificates with an old private key.
This is a refactor, ensure all tests are passing.

fix: avoid potential impossible states

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java

Just skipping a test to unblock CI. There is a weird race condition happening that we need to look at closer. I will address it in a bit but in the meantime this will unblock CI

fix: skip test to unblock ci

---

src/main/java/com/aws/greengrass/clientdevices/auth/iot/Thing.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/events/ThingEvent.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/events/ThingUpdated.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactory.java
src/test/java/com/aws/greengrass/clientdevices/auth/configuration/GroupManagerTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/ThingTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/SessionImplTest.java

Add new Thing Registry interface and emit events when Things are added/updated. This change is somewhat incomplete, as right now timestamps aren't included.
This will be a building block for follow-up PRs which introduce authentication use cases.
Unit tests

feat(wip): add thing registry domain and events

---

src/main/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactory.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/Session.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/SessionImpl.java
src/test/java/com/aws/greengrass/clientdevices/auth/DeviceAuthClientTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/configuration/GroupManagerTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/SessionImplTest.java

This change also removes interface methods that result in updating sessions, which results in sessions becoming immutable by contract instead of by convention (technically the underlying attribute providers can still change so this isn't 100% true)
It's TBD on whether this is actually the behavior we want. But for now this allows us to delete unused code.

refactor: create session using attribute providers

---

src/main/java/com/aws/greengrass/clientdevices/auth/iot/Certificate.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/CertificateRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyIotCertificate.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactory.java
src/test/java/com/aws/greengrass/clientdevices/auth/DeviceAuthClientTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/CertificateFake.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/CertificateRegistryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/SessionImplTest.java

This change removes IoT Core logic from the Certificate Registry -- it now serves as a repository for certificates.
The VerifyIotCertificate use case now inserts certificates into the registry after it validates them.
The MqttSessionFactory retrieves certificates from the Certificate Registry, which removes one cloud API call. However, it is still calling IoT Core to validate  Thing <-> Certificate attachment. Removing that can come later.
This change also introduces a new CertificateFake object helps somewhat with tests, as it allows us to instantiate Certificates without a valid PEM. There are also now test utils for generating client certs. We can slowly improve our test quality over time by migrating to these. Currently the tests …

feat: certificate registry

---

src/main/java/com/aws/greengrass/clientdevices/auth/iot/Thing.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistry.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/ThingTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistryTest.java

Remove Thing versioning logic.
Refer to https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/155/files#r990478687 
We don't want to need to persist version information. We'll come up with a different approach for serializing Thing updates

refactor: remove Thing versioning

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/Certificate.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/CertificateRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyIotCertificate.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/CertificateRegistryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistryTest.java

Enable fully offline authN if we have cached entries in the cert and thing registries.
The verify iot certificate use case will still opportunistically go to the cloud if it thinks we have network. This is ideally the behavior we want.
The Thing <-> Certificate attachment will always use the cached entry, since this was the least intrusive way to get this feature out the door. This will need to change, but since we anyway need more changes to support TTL, I'm calling this good enough for now.
Gave this a good manual test, flipping between network on/off and certificate active/inactive states. We will need to fix our integ tests to ensure this stays working moving …

feat: enable offline authN

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/AuthorizeClientDeviceActionTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClientFake.java

Adds IotAuthClientFake which can be used during testing to avoid mocking IotAuthClient. More work is needed to remove mocks from some of the IPC tests.

test: add IotAuthClientFake

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/BackgroundCertificateRefresh.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/RuntimeConfiguration.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/Certificate.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/CertificateRegistry.java

This PR introduces the `BackgrounCertificateRefresh` infra class whose sole purpose is to re verify stored certificates on a cadence, so when a client goes offline the stored value is one that fairly up to date. We are using a polling mechanism but it might change in the future to a push mechanism connecting to IoT Core and listening for certificate revocations.
We want to give customers a way to ensure their cached values are fairly recent in case the go offline, their devices can still communicate.
Integration test.

feat: refresh certificates in the background

---

src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/events/CAConfigurationChanged.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/handlers/CAConfigurationChangedHandler.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureCustomCertificateAuthority.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureManagedCertificateAuthority.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfiguration.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/CDAConfiguration.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthServiceTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/api/UseCasesTest.java

This is a lower priority refactor but I think it is still important to avoid passing stuff that is not needed with events. Otherwise they might start getting misused leading to code that is coupled and not cohesive in the future.
We are establishing new patterns and other developers might copy them and if we don't tend to this things it might lead to us un-intendedly open the door for code that can get entangled.

refactor: avoid passing the entire configuration with the ca configuration changed event

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java

Fixes a race condition happening on some of the integration tests where the custom CA configuration change where not fully applied before we continued subscribed resulting on the test getting a certificate rotated by the old CA

fix: race condition

---

src/main/java/com/aws/greengrass/clientdevices/auth/api/Result.java
src/main/java/com/aws/greengrass/clientdevices/auth/api/UseCases.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/dto/CreateSessionCommand.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/dto/CreateSessionDTO.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/dto/VerifyThingAttachedToCertificateDTO.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/infra/ThingRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/CreateIoTThingSession.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyThingAttachedToCertificate.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactory.java
src/test/java/com/aws/greengrass/clientdevices/auth/api/UseCasesTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/usecases/ConnectivityInformationUseCasesTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/ThingRegistryTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java

This changes extract the iot client from the registry effectively decoupling them. Before this change we had a boolean method that would mutate the registry. Now we moved the logic into a use case that can be called separately I will further decouple the logic that updates the registry in the next PR but this is the first step.
Refreshing the attached certificates to things is really hard to do without decoupling things. In the next PR I will split things a bit more so I can individually call something that would refresh the thing <-> cert attachements.
Existing tests pass

refactor: extract iot client from registry and decouple update logic

---

src/main/java/com/aws/greengrass/clientdevices/auth/configuration/SecurityConfiguration.java
src/test/java/com/aws/greengrass/clientdevices/auth/configuration/SecurityConfigurationTest.java

**Description of changes:** Updates default client device trust duration to one minute.
**How was this change tested:** Unit tests

fix: update default client device trust duration

---

src/main/java/com/aws/greengrass/clientdevices/auth/infra/NetworkState.java
src/test/java/com/aws/greengrass/clientdevices/auth/infra/NetworkStateTest.java

Network state change events are running in a CRT thread, which means it is not safe to do any meaningful work since we'll be blocking the CRT. This change emits network state change events on an executor service so that callees can safely do whatever work is needed.

fix: dispatch network change events asynchronously

---

src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/BackgroundCertificateRefresh.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/BackgroundCertificateRefreshTest.java

This makes it so that the background refresh runs when the network connectivity is resumed
Improves when we refresh the certificate cache so we opportunistically update the values in it.

feat: refresh certificates when network comes back up

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/BackgroundCertificateRefresh.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/Thing.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/dto/VerifyThingAttachedToCertificateDTO.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/infra/ThingRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/CreateIoTThingSession.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyThingAttachedToCertificate.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/BackgroundCertificateRefreshTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClientFake.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java

This changes the call we make to get the things attached to the core device to use the paginator provided by the aws sdk. It provides a stream that will call all the pages and allow us to process the received response in chunks. I reworked the refresh logic so that we could take advantage of the fact that the response pages can be streamed so we can process one page at a time.
There are still some additional improvements that could be made to improve performance now that we have this streams such as parallel processing of things and certificate updates as well as the cleanup (which can be done on a separate thread).
For clients with cores with more than 100 clients this is required. Otherwise we only ever refresh the first 100d

feat: support pagination on refreshing things and certificates

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/TestHelpers.java

Some tests had been disabled because they were flaky due to the fact that they where just waiting for a call count to be met and not for the actual configuration changes to have take effect. This PR fixes that by introducing a test utility (which we have in other code bases) to wait for an expectation to be eventually true.
Re enable the flaky tests

fix: fix disabled flaky tests

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java

This PR writes the credentials to the file system during the integration tests to better simulate what a real user wold do and avoid mocking unnecessary classes.

fix: avoid unnecessary mocks on integration tests

---

src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyThingAttachedToCertificate.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyThingAttachedToCertificateTest.java

**Issue #, if available:** Network state heuristic is not 100% reliable. In case of false positive Network-UP case, `VerifyThingAttachedToCertificate` usecase does not consider local results when cloud requests fails.
**Description of changes:** Returns local result if `VerifyThingAttachedToCertificate` cloud request fails.
**How was this change tested:** unit tests

fix: return local result when cloud call fails

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCATest.java
src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/certificateauthority/cda.yaml
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/TestHelpers.java

Integration test to ensure ipc subscribers get a new cert when it gets rotated

test: certificate rotation on ca config change for ipc subscribers

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/NetworkStateFake.java

Integration test for the following scenario
Scenario:
1. Client Device connects when GGC is online
2. GGC goes offline
3. Client device certificate is revoked in the cloud
4. Client device is still able to connect to GGC (offline)
5. GGC comes online6. Revoked client device is no longer able to connect to the GGC.

test: certificate revocation offline/online

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java

Test to ensure corrupting the stored client pem does not break authentication

test: corrupt client pem, still authenticates

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/BackgroundRefreshTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java

* Extract the background refresh tests into their own file on integration tests
* Extract the helper to client client certificates into the helpers
* Test to ensure that a corrupted PEM won't break the background refresh and only refresh the ones that are not corrupted

test: background refresh when pem corrupted

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/BackgroundRefreshTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/BackgroundCertificateRefresh.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/BackgroundCertificateRefreshTest.java

This is just a trimmed down version of https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/192 to avoid all those changes. We had to compromise and disable a few tests to avoid increasing the surface area of the changes. We will follow up on this one and ensure the disabled tests don't need to be, but that would require us to change how we mock the time on tests given mocks are not shared between threads.

fix: background refresh logic

---

src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfiguration.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfigurationTest.java

TPM modules do not support adding certificate chains into a single key. This renders TPM users unavailable from providing intermediate certificates.
Introduces a new configuration called certificateChainUri. When provided we will read the certificate chain from it. We are keeping the old configuration that would behave the same if the certificateChainUri is not provided. This will allow TPM users to use the following configuration
```
"certificateAuthority": {
"certificateChainUri": "file:///home/ec2-user/creds/intermediateCA.pem",
"certificateUri": "pkcs11:object=CustomerIntermediateCA;type=cert",
"privateKeyUri": "pkcs11:object=CustomerIntermediateCA;type=private"
}
```
Which effectively allows TPM users to provide intermediate …

feat: add certificate chain config

---

src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/metrics/ClientDeviceAuthMetrics.java
src/main/java/com/aws/greengrass/clientdevices/auth/metrics/MetricsEmitter.java
src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java

Added a metrics folder and the MetricsEmitter class. Wrote a function to enable emitting metrics.
This class can be used to emit the metrics for phase 1 of CDA metrics ingestion.
The metrics themselves will be implemented later.

feat: adding the ability to emit metrics

---

src/main/java/com/aws/greengrass/clientdevices/auth/iot/GreengrassV2DataClientFactory.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java

Using `.httpClient` will create a non-managed SDK HTTP client which means that when the SDK client is closed the HTTP client will NOT close. This is absolutely not what we want in these cases because the SDK client is used and then immediately thrown away. This in turn, causes us to leak HTTP connection managers which are kept alive by the idle connection reaper which will never remove them from tracking because they're never closed.
Using `.httpClientBuilder` instead, will create a managed HTTP client which is properly closed at the same time the SDK client is closed. We are doubtless making this same mistake in the Nucleus and in our other plugins leading to increased memory usage and ultimately leaks.
Also disabling the idle …

fix(sdk-clients): use http client builder to avoid leaks

---

src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/api/AuthorizeClientDeviceActionEvent.java
src/main/java/com/aws/greengrass/clientdevices/auth/api/ClientDevicesAuthServiceApi.java
src/main/java/com/aws/greengrass/clientdevices/auth/metrics/ClientDeviceAuthMetrics.java
src/main/java/com/aws/greengrass/clientdevices/auth/metrics/handlers/AuthorizeClientDeviceActionsMetricHandler.java
src/test/java/com/aws/greengrass/clientdevices/auth/metrics/MetricsTest.java

Created the AuthorizeClientDeviceActions.Success and AuthorizeClientDeviceActions.Failure metrics. When a client device action is successfully or unsuccessfully authorized, an event is emitted and handled by incrementing its respective metric. Both the event and handler are specific to the Authorize Client Device Actions API. 
This change is necessary to allow for tracking the operational status of the Authorize Client Device Actions API. The change was tested by writing unit tests which ensure that the metric is correctly incremented upon events being emitted.

feat: add metrics for the Authorize Client Device Actions API

---

src/main/java/com/aws/greengrass/clientdevices/auth/DeviceAuthClient.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/Component.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactory.java
src/test/java/com/aws/greengrass/clientdevices/auth/DeviceAuthClientTest.java

Adds componentName attribute to the Component session object. This will enable us to look up authZ policies based on component name in the future.

feat: add componentName session attribute

---

src/integrationtests/java/com/aws/greengrass/integrationtests/connectivity/ConnectivityTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/connectivity/config.yaml
src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/RuntimeConfiguration.java
src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/ConnectivityInfoCache.java
src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/ConnectivityInformation.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/ConnectivityInformationTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/usecases/ConnectivityInformationUseCasesTest.java

Cache connectivity information so that it persists across restarts.
If greengrass is restarted offline, previous connectivity information is currently wiped out. This means the server will receive a cert with SAN for `localhost` only, missing other addresses.
Integration test

feat: cache connectivity info

---

src/main/java/com/aws/greengrass/clientdevices/auth/configuration/RuntimeConfiguration.java

Fixes how hostAddresses runtime config is stored in topics

fix: store hostAddresses properly

---

uat/README.md
uat/pom.xml
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/Main.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImpl.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImpl.java
uat/src/main/proto/mqtt_client_control.proto
uat/src/main/resources/log4j2.properties

GGMQ-11, GGMQ-12, GGMQ-19
- Update protocol to pass connection timeout
- Extend gRPC part to handle shutdownAgent/createMqttConnection/closeMqttConnection requests
- Added MqttLibImpl and MqttConnectionImpl and implement methods required for connect and disconnect
- Update README with for build and run commands
- Tune pom.xml
- Use newMqttBuilder without TLS settings
- Switch to log4j2
MQTT client should be able to connect MQTT broker and disconnect from it
At the moment manually, later will covered by unit tests
By submitting this pull request, I confirm that you can use, modify, copy, and …

Ggmq 11 implemenet connect

---

src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitor.java
src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/ConnectivityInformation.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/ConnectivityInformationTest.java

If CIS call fails for some non-retryable exception (ValidationException/ResourceNotFoundException), the hostAddresses cache will be cleared, this change prevents that from happening
unit tests

fix: prevent hostAddresses from being cleared

---

src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitor.java
src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/ConnectivityInformation.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java

Before rotating certificates, check that CIS info has actually changed.
To prevent unnecessary rotations
Unit test

feat: skip cert rotation if connectivity info hasn't changed

---

uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/src/main/proto/mqtt_client_control.proto

Implement subscribe.
Implement unsubscribe.
- Update protocol to send actual subscribe and unsubscribe requests and responses
- Implement subscribe and unsubscribe
MQTT5 test client should be able to subscribe on topics and unsubscribe.
At the moment manually, in phase 2 we are going to cover code with unit tests.

feat(uat): added subscribe and unsubscribe to MQTT5 test client

---

uat/README.md
uat/pom.xml
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCLib.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCLink.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttReceivedMessage.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImpl.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImpl.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImpl.java
uat/src/main/proto/mqtt_client_control.proto

Implementation of  forwardning information from received MQTT message to gRPC server.
- gRPC protocol has been updated to receive message by control side
- Implement passing received message from MQTT connection layer to gRPC client via BiConsumer
- Updated README
- Added GRPCClient and MqttReceivedMessage interfaces to decouple classes.
- Arguments of publish now collected in Message object
- Tune error messages in GRPCControlServer
- Tune code by adding javadoc, replace deprecated calls
Controlled MQTT client should be able to deliver information from receive MQTT message to contol side.
At the moment manually, later will cover code by unit tests.
**Any additional …

feat(uat): implement passing received MQTT message to gRPC server

---

uat/pom.xml

Client should be standalone package.
Build uber jar using shade maven plugin.
Client jar should be standalone to run.
Manually

build(uat): build uber jar with shade maven plugin

---

src/main/java/com/aws/greengrass/clientdevices/auth/session/SessionManager.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/SessionManagerTest.java

Injecting Domain Events into the Session Manager instead of creating a new domain events object with the class.
By creating a new domain events object, the session manager was overriding all of the existing handlers that had been registered in domain events. This caused an issue with the GetClientDeviceAuthToken metrics, since they could not be emitted when domain events was being cleared out.
Updated unit tests.

fix: inject domain events in SessionManager

---

src/main/java/com/aws/greengrass/clientdevices/auth/infra/NetworkStateProvider.java

MQTT client connected method calls a synchronized method which can cause the caller to block. Use the non-blocking connected flag instead.

fix: use non-blocking MQTT client connection status

---

pom.xml
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateHelper.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/ClientCertificateGeneratorTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java

Revert the revert of FIPS changes and change code to not actually use the "BCFIPS" provider which would trigger the hash verification which we know fails. We now use "" as the provider which will use Java's default provider. Customers can (and must) configure Java's default provider to be in FIPS mode if they want FIPS compliance.
Although BC isn't actually doing any crypto now because of this change, I am still switching to BCFIPS to avoid any possible confusion about the FIPS compliance of this module.
Ran cert generation tests with a breakpoint in `FipsStatus.isReady()` to verify it is never called (which would trigger the hash check and subsequent failure).
**Any …

feat: use BCFIPS library, but not BCFIPS provider to avoid failing hash

---

uat/custom-components/client-java-sdk/pom.xml
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/proto/mqtt_client_control.proto

Update SDK-based client to pass information from CONNACK packet to the control
- Extend gRPC protocol by returns MqttConnectReply from CreateMqttConnection call
- Extend protocol by adding Mqtt5ConnAck message
- Added MqttConnection.ConnAckInfo with optional fields
- Added MqttConnection.ConnectResult 
- Update createMqttConnection server side handler to produce response.
- Move objects conversion to separate methods
- Tune existing messages and code to handle fields like optional
In some test scenarios information from CONNACK can be required.
At the moment manually. In phase 2 we are going to add unit and integration tests.
With success test run with IoT Core as …

feat(uat): pass information from CONNACK to control

---

.github/workflows/uat.yml
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/EngineControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java

Extend control by adding Engine.isRunning(), Engine.getAgent()
Added EngineControl.isEngineRunning()
Added Engine.getAgent()
Fix mistake in JAVA UAT CI workflow
We update cucumber scenario to add sentences to check is control engine started and is agent registered.
That change add support of these steps from Control.
At the moment manually, in Phase 2 we going to cover with unit tests.

feat(uat): added isEngineRunning and getAgent to MQTT client control

---

uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/ExampleControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/ConnectionControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/EngineControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java

Implement mapping from string logicalConnectionId to agent/connection
- Added EngineControl.getConnectionControl()
- Added ConnectionControl.setConnectionName()
- Added ConnectionControl.getConnectionName()
- Added AgentControlImpl.getConnectionControl()
- Added build of default connection name value in constructor of ConnectionControlImpl()
- Added EngineControl.getBoundPort()
- Turn AgentControlImpl methods useful only for ConnectionControlImpl to be package private
It require to simplify access to connection control from scenario by only logical name instead of pair agent id and connection id
At the moment manually, in phase 2 we going to cover code by unit tests …

feat(uat): added EngineControl.getConnectionControl() and connection name

---

uat/custom-components/client-java-sdk/pom.xml
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/Main.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/pom.xml
uat/mqtt-client-control/pom.xml
uat/pom.xml
uat/testing-features/pom.xml
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Change pom relations from standalone to parent-children
- pom files are changed to use parent for subprojects
- All plugins/dependecies versions moved to root pom file
- Resolved newly appeared license/checkstype/PMD issues
Subproject testing-features depends on subproject mqtt-client-control and before we have all subprojects as standalone.
CI build

chore(uat): reorganize pom relations to parent-child

---

uat/mqtt-client-control/pom.xml
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/ExampleControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/AgentControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/EngineControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/DiscoveryEvents.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImplTest.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImplTest.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImplTest.java
uat/pom.xml

Create unit tests in control
- Added junit-jupiter-api and mockito-junit-jupiter dependencies.
- Added maven-surefire-plugin
- Added unit tests for ConnectionControlImpl in ConnectionControlImplTest
- Added unit tests for EngineControlImpl in EngineControlImplTest
- Added unit tests for AgentControlImpl in AgentControlImplTest
We should test MQTT client control automatically
On CI

test(uat): added ConnectionControlImplTest in uat MQTT client control

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCLib.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCLink.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImpl.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImplTest.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImplTest.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImplTest.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImplTest.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImplTest.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImplTest.java

Create unit tests of AWS IoT device SDK client
- Added unit tests for GRPCLibImpl
- Added unit tests for GRPCLinkImpl
- Tune interfaces using NonNull
- Decouple implementations by using factory to allow unit testing
- Added constructors for test
- Change to correct ArgumentMatchers.any()
Code of MQTT client based on AWS IoT device SDK should be covered by unit tests.
These unit tests will be running during project build on CI.

test(uat): added unit tests for GRPCLibImpl GRPCLinkImpl

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

- added ability to select any free port to start control
- to improve code reliability
**Logs:**
```
[main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:37843.
```

 feat(uat): added autoselect for control port

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Multi-homed broker is not supported
- Add support of multi-homed broker but implement iteration over addresses in building block of connect
- Add comments in gRPC protocol about semantic and format of TLS message
- Remove local check of broker address connectivity
Currently implementation is use just first address of broker which available locally. 
It will not works for remote clients.
That cons should be fixed.
No specific tests for that code due to it is building blocks
**Scenario results:**
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2023-04-19 18:02:07.964 [main] GreengrassContextModule - Extracting …
```

feat(uat): add support of multi-homed broker

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCLib.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/Main.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImpl.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImplTest.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImplTest.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/EngineControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImplTest.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/components/recipes/client_java_sdk.yaml
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Multi-homed control is not supported
- Add detection of control addresses and pass to client
- Allow SDK-base MQTT client to receive multiple IP/host of control
Currently agent got hard coded 127.0.0.1 as address of control.
That limit clients to be run only locally.
Implementation is changed to get actual list of IP addresses how control can be reached and pass it to the agent arguments.
Unit test added to new method of control.
Other parts can be verified during scenario run.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

feat(uat): add support of remote clients and multi-homed control

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImpl.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImplTest.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/ExampleControl.java
uat/proto/mqtt_client_control.proto
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Update control and SDK client to request MQTT 3.1.1 connections
- Add Mqtt311ConnectionImpl.java with frame code of the MQTT 3.1.1 connection
- Add mqtt50 flag in MqttLib.ConnectionParams
- Update check of version in incoming gRPC connect request
- Update connection factory to produce Mqtt311ConnectionImpl
- Update unit tests of MqttLibImpl
- Update control's scenario and main to receive and handle use mqtt 5.0 flag
- Add logging of discovered info about broker for manual testing
We are going to add posibility to establish MQTT 3.1.1 connections to existing SDK-based agent.
As a first step we need update control used as manual testing tool and agent common code to allow protocol version 3.1.1
**How …

feat(uat): allow requests with MQTT v3.1.1 proto version

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Disconnect thing
- Added new step to disconnect
to use in feature testing
On CI
```log
And I create client device "clientDeviceTest"...............................passed
When I associate "clientDeviceTest" with ggc................................passed
And I update my Greengrass deployment configuration, setting the component aws.greengrass.clientdevices.Auth configuration to:.passed
And I update my Greengrass deployment configuration, setting the component …
```

feat(uat): added step disconnect in MqttControlSteps

---

uat/custom-components/client-java-sdk/README.md
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/mqtt-client-control/README.md
uat/proto/mqtt_client_control.proto

Implement MQTT 3.1.1 connect
Implement MQTT 3.1.1 disconnect
- Implement Mqtt311ConnectionImpl.start() and .disconnect() methods.
- Update README of control to describe third argument 
- Update README of client to describe limimtations
- Update protocol to mark MqttConnectReply.error as optional
Connect and disconnect methods are required to provide full functionality of MQTT 3.1.1 client
Manually until unit tests and full client's logic will be used in scenarios
Note: publish/subscribe/unsubscribe not yet implemented and do nothing
To local mosquitto broker:
Control:
```
$ ./run_for_mosquitto_311.sh
[INFO ] 2023-04-24 14:22:37.694 [main] …
```

feat(uat): add connect/disconnect implementation to MQTT 3.1.1 client

---

uat/custom-components/client-java-sdk/README.md
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java

Implement MQTT 3.1.1 subscribe
Implement MQTT 3.1.1 unsubscribe
Implement MQTT 3.1.1 publish
- Added implementation of subscribe
- Added implementation of unsubscribe
- Added implementation of publish
- Updated README of client to describe limitations
To run scenarios also on MQTT v3.1.1 protocol.
At the moment manually, using control as a standalone program.
**Test logs:**
Control:
```
[INFO ] 2023-04-24 22:03:21.788 [main] EngineControlImpl - MQTT client control gRPC server started, listening on 47619
[INFO ] 2023-04-24 22:03:30.588 [grpc-default-executor-0] GRPCDiscoveryServer - RegisterAgent: agentId agent1
[INFO ] 2023-04-24 22:03:30.639 [grpc-default-executor-0] …
```

feat(uat): add subscribe/unsubscribe/publish to MQTT v3.1.1 client

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Extend steps to be able to use MQTT 3.1.1 protocol
- Added ability to select version of MQTT protocol used for MQTT connect 
- Tune javadoc comments
Support of MQTT 3.1.1 was requested

feat(uat): extend steps to be able to use MQTT 3.1.1 protocol 

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImplTest.java

Create unit tests of AWS IoT device SDK client
- Added unit tests for Mqtt311ConnectionImpl
- Fix typo in Mqtt311ConnectionImpl
Cover MQTT v3.1.1 client by unit tests to ensure class works as expected
As unit tests it run on CI

test(uat): add unit tests for Mqtt311ConnectionImpl

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

- added GGAD-1-T14 scenario using OTF and new building blocks
- to test bridge functionality
```
And I create client device "localMqttSubscriber"............................passed
And I create client device "iotCorePublisher"...............................passed
When I associate "localMqttSubscriber" with ggc.............................passed
And I update my Greengrass deployment configuration, setting the component aws.greengrass.clientdevices.Auth configuration …
```

feat(uat): implement ggad t14

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

T1 was parameterized by version of MQTT protocol: “v5” and “v3”
- added  parameters for scenario GGMQ-1-T1;
- added reason code for disconnect.
```
java -Dggc.archive=./greengrass-nucleus-latest.zip -Dtest.log.path=./logs -Dtags=GGMQ -jar uat/testing-features/target/client-devices-auth-testing-features.jar
```
```
And I create client device …
```

feat(uat): added parameters in T1 scenario and reason code for disconnect

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Provide CONNACK info from Mosquitto client
- Rename MQTT version enum members in protocol
- Change default disconnect reason to 0 (normal disconnect) from 4 (will should be sent).
- Fix typos
When C++ code of protocol is generated we got an conflict of MQTT version names with defines in mosquitto.h
In results in mosquitto.h and protocol headers can't be included in the same source file.
CI

fix(uat): rename MQTT versions enum in protocol due to conflict with mosquitto

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-mosquitto-c/scripts/build_debug.sh
uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto

Implement publish in Mosquitto client
- Implement publishing in Mosquitto based CPP client
- Tune logging in control's scenario and in mosquitto client
Mosquitto client should be able to publish MQTT messages.
Tested manually using IoT Core test MQTT client, when subscribe on '#' filter published message has been appeared as expected. Test run using control application for IoT core broker.
**Test log**
Control:
```
[INFO ] 2023-05-08 20:13:59.128 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] EngineControlImpl - MQTT client control gRPC server started, listening on 47619
[INFO ] 2023-05-08 20:13:59.911 [grpc-default-executor-0] …
```

feat(uat): implement publish in mosquitto client

---

uat/custom-components/client-mosquitto-c/README.md
uat/custom-components/client-mosquitto-c/scripts/build_docker.sh
uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/custom-components/client-mosquitto-c/src/logger.cpp

Implement unsubscribe in the Mosquitto-based client
- Implement unsubscribe feature
- Fix bug in AsyncResult creation and provide 3'th constructor
- Fix bug in char** leak by usage of std::vector
- Remove names of unused arguments
- Update limitations section in README
- Tune logging output
Test client requires unsubscribe MQTT feature
At the moment manually, later client will be used in the scenarios.
**Test logs**:
Control:
```
[INFO ] 2023-05-10 18:52:46.904 [grpc-default-executor-0] GRPCDiscoveryServer - RegisterAgent: agentId agent_mosquitto
[INFO ] 2023-05-10 18:52:46.916 [grpc-default-executor-0] GRPCDiscoveryServer - DiscoveryClient: agentId agent_mosquitto …
```

feat(uat): implement unsubscription in mosquitto-based client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

Added publish to paho client
- added method publish
run command **mvn exec:java** in paho-agent module 
Control:
```
INFO ] 2023-05-22 19:37:26.276 [grpc-default-executor-1] GRPCDiscoveryServer - RegisterAgent: agentId best-thing-akezhan
[INFO ] 2023-05-22 19:37:26.324 [grpc-default-executor-1] GRPCDiscoveryServer - DiscoveryClient: agentId best-thing-akezhan address 127.0.0.1 port 36869
[INFO ] 2023-05-22 19:37:26.325 [grpc-default-executor-1] EngineControlImpl - Created new agent control for best-thing-akezhan on 127.0.0.1:36869
[INFO ] 2023-05-22 19:37:26.325 [grpc-default-executor-1] ExampleControl - Agent …
```

feat(uat): added publish to java-paho-agent

---

uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

resolve issue when control uses outdated address of restart
- Fix bug in control when agent is restarted
- Add more tags in scenarios
'no local' feature should be tests
By running scenarios
With sdk-java client
```
$ ./run_test_aws_T100_sdk.sh 
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2023-05-19 18:14:58.694 [main] GreengrassContextModule - Extracting greengrass-nucleus-latest.zip into /tmp/gg-testing-15744393887570050675/greengrass
[INFO ] 2023-05-19 18:14:59.371 [main] LoggerSteps - OTF Version is otf-1.1.0-SNAPSHOT
[INFO ] 2023-05-19 18:14:59.371 [main] LoggerSteps - Attaching thread …
```

fix(uat): resolve issue when control uses outdated address of restart

---

uat/README.md
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Test scenario T1 was extended with T2, T6 and T19
- T1 was extended with T2, T6 and T19
run command **mvn exec:java** in paho-agent module 
```
<testcase classname="GGMQ-1" name="GGMQ-1-T1-v3-sdk-java: As a customer, I can connect, subscribe, publish and receive using client application to MQTT topic" time="108.319">
<system-out>
<![CDATA[Given my device is registered as a Thing....................................passed
And I create client device …
```

feat(uat): t1 was extended with t2, t6 and t19

---

uat/custom-components/client-java-sdk/README.md
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

added retainFlag in publish and retainHanding in subscribe
added GGMQ-1-RETAIN scenario
added retainFlag in publish and retainHanding in subscribe
added GGMQ-1-RETAIN scenario
run command **mvn exec:java** in paho-agent module 
```
<testcase classname="GGMQ-1" name="GGMQ-1-T111-v3-sdk-java: As a customer, I can configure local MQTT messages to be forwarded to a PubSub topic" time="115.559">
<system-out>
<![CDATA[Given my device is registered as a Thing....................................passed
When I create a Greengrass …
```

feat(uat): added retainFlag in publish and retainHanding in subscribe

---

.license/style.xml
uat/custom-components/client-mosquitto-c/pom.xml
uat/custom-components/client-mosquitto-c/scripts/export_docker_runner.sh
uat/custom-components/client-mosquitto-c/scripts/produce_docker_container.sh
uat/custom-components/client-mosquitto-c/scripts/rebuild_docker.sh
uat/custom-components/client-mosquitto-c/scripts/rebuild_linux_debug.sh
uat/custom-components/client-mosquitto-c/scripts/rebuild_linux_prod.sh
uat/custom-components/client-mosquitto-c/scripts/rebuild_windows.bat
uat/custom-components/client-mosquitto-c/scripts/run_docker.sh
uat/custom-components/client-mosquitto-c/src/CMakeLists.txt
uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/mqtt-client-control/pom.xml
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/AgentControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/EventFilter.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/SubscribeReasonCode.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEvent.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImplTest.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImplTest.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEventTest.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/components/recipes/client_mosquitto_c.yaml
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Setup retained message control (tune)
Investigate random errors during running test scenarios
- Fix bug with pointer to dead std::string ca in mosquitto c client code
- Tune logging in mosquitto c client code
- Add maven license check to mosquitto c client code
- Rework GGMQ-1-T1 to remove invalid part from GGAD-1-T2
- Extend GGMQ-1-T14 to be outline and run for 2 clients and both MQTT versions
- Tune GGMQ-1-T101
- Tune steps names
- Extend control's stopAgent by adding ability to skip sending commands to agent and use it when agent calls unregister
- Add `retain` flag check to message event filter and 4 unit tests
- Change SUCCESS to GRANTED_QOS_0 in Subscribe reason code
At the moment code and …

fix(uat): fix random errors during running test scenarios

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/ConnectionControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImpl.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImplTest.java
uat/proto/mqtt_client_control.proto
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

added userProperties for connect, publish and receive
- added userProperties for connect, publish and receive Mqtt V5.0
run command **mvn exec:java** in paho-agent module 
Control's log:
```
INFO ] 2023-06-07 14:50:06.228 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] EngineControlImpl - MQTT client control gRPC server started, listening on 47619
[INFO ] 2023-06-07 14:50:12.555 [grpc-default-executor-0] GRPCDiscoveryServer - RegisterAgent: agentId paho-java-agent
[INFO ] 2023-06-07 14:50:12.590 [grpc-default-executor-0] GRPCDiscoveryServer - DiscoveryClient: agentId paho-java-agent …
```

feat(uat): added userProperties for connect, publish and receive

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

added unsubscribe to paho-java-client
- added unsubscribe to paho-java-client
- sync client was changed to async client for Mqtt v3.1.1
- added wait time for missed methods
run command mvn exec:java in paho-agent module
**Mqtt V5 client's log:**
```
[INFO ] 2023-06-13 17:49:58.873 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as best-thing-akezhan...
[INFO ] 2023-06-13 17:49:59.396 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-06-13 17:49:59.432 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:41253
[INFO ] …
```

feat(uat): added unsubscribe to paho-java-client 

---

uat/README.md
uat/custom-components/client-mosquitto-c/README.md
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/mqtt-client-control/pom.xml
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Both GGMQ-1-T13-vX failed on Windows and linux
- Update GGMQ-1-T13 to fix CDA misconfigure issue and add mosquitto-c client
- Fix bug in missing reason code in publish of mosquitto client
- Updated uat/README.md by adding requirements and build steps description
- Update mosquitto REAME.md by adding commands for docker build and limitations
- Fix missing jar.plugin.version in control's pom.xml
Scenarios in T13 outline are invalid
Run scenarios locally manually and on CI
```
[INFO ] 2023-06-14 01:18:24.535 [main] StepTrackingReporting - Passed: 'GGMQ-1-T13-v3-sdk-java: As a customer, I can connect two GGADs and send message from one GGAD to the other …
```

fix(uat): resolve issues in mosquitto/publish and in T13 scenarios

---

.license/style.xml
uat/README.md
uat/custom-components/client-mosquitto-c/.gitignore
uat/custom-components/client-mosquitto-c/README.md
uat/custom-components/client-mosquitto-c/pom.xml
uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/custom-components/client-mosquitto-c/src/MqttLib.cpp
uat/custom-components/client-mosquitto-c/src/MqttLib.h
uat/custom-components/client-python-paho/pom.xml
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/ExampleControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/ConnectionControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImpl.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/ConnectionControlImplTest.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Set/unset user property(es) in mosquitto client
- Add handling of MQTT v5.0 properties in all requests and responses of mosquitto client
- Update control to be able to get and provide MQTT v5.0 user properties for connect/disconnect subscribe/unsubscribe publish and receiving messages
- Update mqtt steps by adding user property list currently is null
- Tune error handling in mosquitto client
- Do not pass user properties from control app if MQTT v3 is selected
- Fix mistypes in log lines
- Update readme files to provide actual commands
- Change license check styles names by adding suffix _style
User properties should be transmitted as well as received in mosquitto client
**How was this change …

feat(uat): handle user properties in mosquitto client

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

feat(uat): added new step for scenario
- Extend test scenario
- Add new step
In GGMQ-1-T102 we testing ability to subscribe with retain handling
```
When I associate "subscriber" with …
```

feat(uat): added new step for scenario

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttLibImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java

Added user properties to missing methods
- added user properties to missing methods
- deleted unnecessary class
- added warning logs to mqtt3 connection implemention
- fixed reasonCode on publish in paho-client
for correct working of clients
**Client' log:**
```
[INFO ] 2023-06-15 19:03:11.668 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as best-thing-akezhan...
[INFO ] 2023-06-15 19:03:12.158 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-06-15 19:03:12.185 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:35723
[INFO ] …
```

feat(uat): added user properties to missing methods

---

uat/README.md
uat/custom-components/client-mosquitto-c/pom.xml
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Connection error in mosquitto client
- Add EMQX log line check  after deployment and before starting other operations
- Update README.md by add region to env variables
- Exclude build of mosquitto client from license check
- Tune error log message
That change try to resolve issues when client can't establish MQTT connection
Run all scenarios and check fail reason. When no related to connect failed that means problem is resolved.
```
[INFO ] 2023-06-16 02:13:05.499 [main] StepTrackingReporting - Passed: 'GGMQ-1-T1-v3-sdk-java: As a customer, I can connect, subscribe/publish at QoS 0 and 1 and receive using client application to MQTT topic'
[INFO ] …
```

fix(uat): attempt to fix connection failed issue

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

Fixed reasonCode on publish in paho-client
- fixed reasonCode on publish in paho-client
for correct working of clients
**Client' log:**
```
When I associate "subscriber" with ggc......................................passed
When I …
```

fix(uat): fixed reasonCode on publish in paho-client 

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java

Added logs for user properties
- Added logs for user properties
for correct working of clients
**SDK Client' log:**
```
[INFO ] 2023-06-19 13:15:28.549 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as best-thing-akezhan...
[INFO ] 2023-06-19 13:15:28.895 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-06-19 13:15:28.937 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:46393
[INFO ] 2023-06-19 13:15:28.945 [main] GRPCLinkImpl - Handle gRPC requests
[INFO ] 2023-06-19 13:15:28.945 [main] GRPCControlServer - Server …
```

feat(uat): added logs to user properties

---

uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto

Set payload content type (publish)
- Add contentType field to Mqtt5Message of protocol
- Add handling contentType in mosquitto client for PUBLISH message for both TX and RX sides
- Update application of Control to pass content type to publish request and log content type from received messages
Currently manually by run Control as application.
In future we will add scenario to test that feature.
Control:
```
[INFO ] 2023-06-19 19:09:28.925 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] ExampleControl - Control: port 47619, with TLS, MQTT v5
[INFO ] 2023-06-19 19:09:29.215 …
```

feat(uat): add handling content type for RX/TX to mosquitto client; update Control

---

uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/grpc_client_server/grpc_discovery_client.py
uat/custom-components/client-python-paho/src/logger_setup/logger_setup.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

- Implement Disconnect feature
- Update logger formatting
MQTT connect and disconnect are successful, other commands are not implemented. Linking and shutdown steps are successful.
```
client-python-paho.exe python-paho-mqtt
[DEBUG] 2023-06-19 23:16:26.198 asyncio - Using selector: SelectSelector
[INFO ] 2023-06-19 23:16:26.201 GRPCLib - Initialize gRPC library
[INFO ] 2023-06-19 23:16:26.201 GRPCLink - Making gPRC client connection with 127.0.0.1:47619 as python-paho-mqtt...
[INFO ] 2023-06-19 23:16:26.357 GRPCLink - Client connection with Control is …
```

feat(uat): implement disconnect from control and broker

---

uat/custom-components/client-java-paho/README.md
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/README.md
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Integrate paho java client to existing scenarios
- Update existing scenario outline by adding example with paho-java client MQTT v3/v5 
- Fix bug in paho-java MQTT v3 with sending single reason code in subscribe() and unsubscribe()
- Update README files of paho-java and sdk-java clients
Currently paho java client is used only in T101 and T102 scenarios and do not pass base checks
Run scenarios on codeBuild

feat(uat): integrate paho java client to existing scenarios

---

uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto

Set payload format indicator
- Update protocol to add optional payloadFormatIndicator to message Mqtt5Message
- Add handling of optional payload format indicator to mosquitto client in both tx and rx directions of PUBLISH
- Update Control app to pass payload format to publish() request and log it from received messages
Manually by run Control as standalone application
Please find the lines related to 'payload format indicator'
Control output
```
[INFO ] 2023-06-20 18:44:58.286 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] ExampleControl - Control: port 47619, with TLS, MQTT v5
[INFO ] 2023-06-20 18:44:58.490 …
```

feat(uat): update protocol, mosquitto client, control app to handle payload format indicator

---

uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/EventFilter.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Implement Retain As published flag
- Add GGMQ-1-T103 scenario outline to test 'retain as published' feature
- Update MqttControlSteps by adding receivedRetain variable and use it in receive steps 
- Update EventFilter to allow reset retain matching
- Tune logging of MqttControlSteps
- Tune steps sentences
- Add  explicit disconnect for all devices
We should be able to test 'retain as published' flag has effect
Run scenarios including new GGMQ-1-T103 on codeBuild
```
[INFO ] 2023-06-20 22:06:20.328 [main] StepTrackingReporting - Passed: 'GGMQ-1-T1-v3-sdk-java: As a customer, I can connect, subscribe/publish at QoS 0 and 1 and receive using client …
```

feat(uat): add 'retain as published' handling and T103 as well

---

uat/custom-components/client-python-paho/README.md
uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

- Implement MQTT Publish feature
- Fix bugs
MQTT connect, publish and disconnect are successful, other commands are not implemented. Linking and shutdown steps are successful.
```
client-python-paho.exe python-paho-mqtt
[DEBUG] 2023-06-21 12:37:01.059 asyncio - Using selector: SelectSelector
[INFO ] 2023-06-21 12:37:01.061 GRPCLib - Initialize gRPC library
[INFO ] 2023-06-21 12:37:01.061 GRPCLink - Making gPRC client connection with 127.0.0.1:47619 as python-paho-mqtt...
[INFO ] 2023-06-21 12:37:01.322 GRPCLink - Client connection with Control is …
```

feat(uat): implement publish

---

.github/workflows/otf.yml

Tune OTF UATS startup events
- Enable for push to uat-dev
- Enable run otf uats manually for selected branch
Avoid workflow failures on PRs created from external repos
Run scenarios automatically on push to uar-dev
Run scenarios by request
Automatically by github CI

ci(uat): enable otf uats on for push and manually selected branch

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java

Set payload content type in PUBLISH tx/rx
Set payload format indicator in PUBLISH tx/rx
- Implement handling of content type in PUBLISH  for both TX and RX directions
- Implement handling of payload format indicator in PUBLISH  for both TX and RX directions
- Added stub with warning for MQTT v3.1.1 client
- Fix bug in CONNECT when user properties does not used
- Fix bug in SUBSCRIBE when user properties set multiple times
- Simplify code related to user properties handling
Implementation of new features of MQTT v5.0
Manually using control application and checking log output.
Control app
```
[INFO ] 2023-06-22 16:59:42.482 …
```

feat(uat): add payload format indicator; content type; fix bugs

---

uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

https://klika-tech.atlassian.net/browse/GGMQ-257
deleted paho and mosquitto-c clients from t2
- deleted paho and mosquitto-c clients from t2
In GGMQ-1-T2 we testing ability to publish with different qos
For all clients and all versions:
```
And I create client device "clientDeviceTest"...............................passed
When I associate "clientDeviceTest" with …
```

fix(uat): deleted paho and mosquitto-c clients from t2

---

uat/custom-components/client-python-paho/README.md
uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

- Implement MQTT Subscribe feature
MQTT connect, subscribe, publish and disconnect are successful, other commands are not implemented. Linking and shutdown steps are successful.
```
[DEBUG] 2023-06-22 14:30:49.402 asyncio - Using selector: SelectSelector
[INFO ] 2023-06-22 14:30:49.405 GRPCLib - Initialize gRPC library
[INFO ] 2023-06-22 14:30:49.407 GRPCLink - Making gPRC client connection with 127.0.0.1:47619 as python-paho-agent...
[INFO ] 2023-06-22 14:30:49.601 GRPCLink - Client connection with Control is …
```

feat(uat): implement subscribe

---

uat/custom-components/client-ipc/src/main/java/com/aws/greengrass/testing/ipc/IpcClientMainRouter.java
uat/custom-components/client-ipc/src/main/java/com/aws/greengrass/testing/ipc/LocalIpcPublisher.java
uat/custom-components/client-ipc/src/main/java/com/aws/greengrass/testing/ipc/LocalIpcSubscriber.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

GGMQ-1-T8 failed on Windows
- Rework IPC client to serialize subscribe/publish in the same IPC connection
- Fix errors propagation in IPC client
- Tune error logging in IPC client
Fix run T8 on Windows
Run GGMQ-1-T8 scenarios on Windows and Linux.
**Test result:**
Windows:
```
[INFO ] 2023-06-23 13:25:40.848 [main] StepTrackingReporting - Passed: 'GGMQ-1-T8-v3-sdk-java: As a customer, I can configure local MQTT messages to be forwarded to a PubSub topic'^M
[INFO ] 2023-06-23 13:25:40.848 [main] StepTrackingReporting - Passed: 'GGMQ-1-T8-v3-paho-java: As a customer, I can configure local MQTT messages to be forwarded to a PubSub topic'^M
[INFO ] 2023-06-23 13:25:40.848 …
```

fix(uat): resolve thread unsafe operations in IPC client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

added content type to paho  client
- added content type to paho  client
to implement Mqtt 5.0 features
*Paho client's logs*:
```
[INFO ] 2023-06-22 18:55:37.022 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as best-thing-akezhan...
[INFO ] 2023-06-22 18:55:37.403 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-06-22 18:55:37.442 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:38373
[INFO ] 2023-06-22 18:55:37.532 [main] GRPCLinkImpl - Handle gRPC requests
[INFO ] 2023-06-22 18:55:37.532 [main] …
```

feat(uat): added content type to paho-java-client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

added payload format indicator to paho  client
- added payload format indicator to paho  client
to implement Mqtt 5.0 features
*Paho client's logs*:
```
[INFO ] 2023-06-22 18:55:37.022 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as best-thing-akezhan...
[INFO ] 2023-06-22 18:55:37.403 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-06-22 18:55:37.442 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:38373
[INFO ] 2023-06-22 18:55:37.532 [main] GRPCLinkImpl - Handle gRPC requests
[INFO ] 2023-06-22 …
```

feat(uat): added payload format indicator to paho-java-client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/Event.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/EventFilter.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEvent.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEventTest.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Set payload format indicator
- Add new steps to set tx and expected rx payload format indicator
- Add test cases for payload format indicator handling
- Join all MQTT v5 features test case to GGMQ-1-T102
- Add ability to filter messages by value of payload format indicator
- Fix bug in paho-java client when payload format indicator field of intermediate message is not handled
- Add unit tests for new filter feature
- Add @SkipOnWindows tag to scenarios
Require to test payload format indicator MQTT v5.0 feature
- 5 unit tests for have been added to control
- new test cases in GGMQ-1-T102 scenario outline has been added for 3 clients
first run
```
[INFO …
```

feat(uat): add test cases to send and receive messages with payload format indicator

---

.github/workflows/otf.yml
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Set/unset non local publishing
- Update GGMQ-1-T102 by adding test cases for subscribe 'non local' feature
'no local' feature should be tested
By running scenarios on CodeBuild
```
[INFO ] 2023-06-26 22:00:13.320 [main] StepTrackingReporting - Passed: 'GGMQ-1-T102-v5-sdk-java: As a customer, I can use publish retain flag and subscribe retain handling as expected'
[INFO ] 2023-06-26 22:00:13.321 [main] StepTrackingReporting - Passed: 'GGMQ-1-T102-v5-mosquitto-c: As a customer, I can use publish retain flag and subscribe retain handling as expected'
[INFO ] 2023-06-26 22:00:13.321 [main] StepTrackingReporting - Passed: 'GGMQ-1-T102-v5-paho-java: As a …
```

feat(uat): add test cases for 'no local' feature

---

uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/grpc_client_server/grpc_discovery_client.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

- Implement delivery of received MQTT message
MQTT connect, subscribe, publish, delivery of received MQTT message and disconnect are successful, other commands are not implemented. Linking and shutdown steps are successful.
```
[DEBUG] 2023-06-26 13:05:23.198 asyncio - Using selector: SelectSelector
[INFO ] 2023-06-26 13:05:23.201 GRPCLib - Initialize gRPC library
[INFO ] 2023-06-26 13:05:23.201 GRPCLink - Making gPRC client connection with 127.0.0.1:47619 as python-paho-agent...
[INFO ] 2023-06-26 13:05:23.363 …
```

feat(uat): implement delivery of received message

---

uat/custom-components/client-python-paho/README.md
uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

- Implement unsubscribe
MQTT connect, subscribe, unsubscribe, publish, delivery of received MQTT message and disconnect are successful. Linking and shutdown steps are successful.
```
[DEBUG] 2023-06-27 18:51:18.939 asyncio - Using selector: SelectSelector
[INFO ] 2023-06-27 18:51:18.944 GRPCLib - Initialize gRPC library
[INFO ] 2023-06-27 18:51:18.945 GRPCLink - Making gPRC client connection with 127.0.0.1:47619 as python-paho-agent...
[INFO ] 2023-06-27 18:51:19.532 GRPCLink - Client connection with Control is …
```

feat(uat): implement unsubscribe for python paho client

---

uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/EventFilter.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEvent.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

add tx/rx content type and extend t102 with content type
- Add content type steps
- Extend t102 with content type
- Rename t101
- Rename t102
Testing  MQTT v5.0 content type feature
```
When I associate …
```

feat(uat): add steps for tx and rx content type and extend t102

---

uat/README.md
uat/custom-components/client-java-sdk/README.md
uat/custom-components/client-java-sdk/pom.xml
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/pom.xml

SDK-based client does not call onMqttDisconnect when client disconnected
- Add call to trigger disconnect event
- Resolve issue NPE in onMqttDisconnect
- Add more callbacks to MQTT v3.1.1 client
- Use latest CRT version with new callbacks
- Add exception logging for code called in executorService
- Update two README files
- Update control to make 10 sec pause between subscribe and publish to simplify manual tests
Bug so not allow to send disconnect event to control from sdk-java client
Manually. 
Use client, control app and local mosquitto broker and terminate it in the middle between client's subscribe and publish.
Check logs in client and control. Ensure control …

fix(sdk-java-client): add passing event about disconnect

---

uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto

Set/unset message expiry interval
- Update protocol by adding optional field messageExpiryInterval to Mqtt5Message
- Update mosquitto client to handle message expiry interval in PUBLISH message in both directions
- Update control application to send message expiry interval and log it from received messages
- Tune logging in mosquitto client and control
New MQTT v5.0 feature message expiry interval should be handled
Currently manually by running Control as application with hard-coded scenario.
Later by adding new cucumber scenario.
Control:
```
[INFO ] 2023-06-30 15:27:50.490 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] …
```

feat(uat): handle message expiry interval in mosquitto client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

Set message expiry interval for java-paho-client 
- Update java-paho client to handle message expiry interval in PUBLISH message in both directions
- Update java-paho to log message expiry interval from received messages
New MQTT v5.0 feature message expiry interval should be handled
Currently manually by running Control as application with hard-coded scenario.
Later by adding new cucumber scenario.
Control:
```
[INFO ] 2023-07-01 14:53:46.812 [grpc-default-executor-0] GRPCDiscoveryServer - RegisterAgent: agentId best-thing-akezhan
[INFO ] 2023-07-01 14:53:46.897 [grpc-default-executor-0] GRPCDiscoveryServer - DiscoveryClient: agentId …
```

feat(uat): add message expiry interval for java-paho-client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

Set no local pulishing for java-paho-client 
- Update java-paho client to use no local pulishing in subscribe method
New MQTT v5.0 feature no local publishing is using.
Currently manually by running Control as application with hard-coded scenario.
Later by adding new cucumber scenario.
Control:
```
[INFO ] 2023-07-01 14:53:46.812 [grpc-default-executor-0] GRPCDiscoveryServer - RegisterAgent: agentId best-thing-akezhan
[INFO ] 2023-07-01 14:53:46.897 [grpc-default-executor-0] GRPCDiscoveryServer - DiscoveryClient: agentId best-thing-akezhan address 127.0.0.1 port 34333
[INFO ] 2023-07-01 14:53:46.899 [grpc-default-executor-0] EngineControlImpl - Created …
```

feat(uat): add no local publishing to java-paho-client

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java

Set message expiry interval for java-sdk-client 
- Update java-sdk client to handle message expiry interval in PUBLISH message in both directions
- Update java-sdk to log message expiry interval from received messages
New MQTT v5.0 feature message expiry interval should be handled
Currently manually by running Control as application with hard-coded scenario.
Later by adding new cucumber scenario.
Control:
```
2023-07-05 12:10:15.343 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] EngineControlImpl - MQTT client control gRPC server started, listening on 47619
[INFO ] 2023-07-05 12:10:27.228 [grpc-default-executor-0] …
```

feat(uat): add message expiry control to java-sdk-client

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/custom-components/client-mosquitto-c/src/GRPCControlServer.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h
uat/custom-components/client-mosquitto-c/src/MqttLib.cpp
uat/custom-components/client-mosquitto-c/src/MqttLib.h
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/proto/mqtt_client_control.proto
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Implement request/response
- Extend protocol by adding Response Topic, Correlation data, Request Response Information
- Update mosquitto client to handle PUBLISH Response Topic in Tx and Rx directions
- Update mosquitto client to handle PUBLISH Correlation Data in Tx and Rx directions
- Update mosquitto client to handle CONNECT Request Response Information
- Update Control application by sending CONNECT Request Response Information, PUBLISH Response Topic, Correlation Data and log it on receive
- Fix bug in sdk client when disconnect sent on dead executor service
- Fix mem leak bugs related to property reading
- Tune mosquitto client and control logging
Capable to test 4 request/response features on …

feat(uat): implement request/response in mosquitto client and control app

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/custom-components/client-mosquitto-c/README.md

Implement request/response features
- Implement PUBLISH Response Topic feature for both Tx and Rx directions
- Implement PUBLISH Correlation data feature for both Tx and Rx directions
- Implement CONNECT Request Response Information feature for Tx
- Implement CONNACK Response Information feature for Rx
- Extend fix of executorService usage to receive message
- Reorder property handling to be the same order as in MQTT v5.0 spec
We need support request/response MQTT v5.0 features in SDK-java client
Currently manually by run Control as application.
Later by creating scenario to test these 4 features.
Control:
```
[INFO ] 2023-07-06 15:41:56.077 …
```

feat(uat): implement request response features in sdk-java client

---

uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/main.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

- Implement handling user properties
MQTT connect, subscribe, unsubscribe, publish, delivery of received MQTT message and disconnect are successful. Linking and shutdown steps are successful.
```
[DEBUG] 2023-07-05 16:46:45.413 asyncio - Using selector: SelectSelector
[INFO ] 2023-07-05 16:46:45.415 GRPCLib - Initialize gRPC library
[INFO ] 2023-07-05 16:46:45.416 GRPCLink - Making gPRC client connection with 127.0.0.1:47619 as python-paho-agent...
[INFO ] 2023-07-05 16:46:45.593 GRPCLink - Client connection with …
```

feat(uat): implement handling user properties for python paho client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h

Clients retry MQTT connection even when first attempt failed and control lost it
- Set long reconnect timeout (1 day) in SDK java and mosquitto C clients
- Disable reconnect feature in paho java client
- Add closing of library client when connection was not successful
- Resolve usage of terminated ExecutorService issue in paho and sdk clients
- Use keep alive and clean session in paho java client
- Add FIXME tags for future changes
Connections doubled and have a race
Only manually when local broker is not ready at first address attempt.
By submitting this pull request, I confirm that you can use, …

fix(uat): resolve clients uncontrolled reconnect issue

---

uat/README.md
uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

- Implement handling payload format indicator
- Implement handling message expiry interval
- Implement handling content type
- Add Python Paho client to 102 scenario
MQTT connect, subscribe, unsubscribe, publish, delivery of received MQTT message and disconnect are successful. Linking and shutdown steps are successful.
T102 scenario run.
```
[DEBUG] 2023-07-07 18:51:01.377 asyncio - Using selector: SelectSelector
[INFO ] 2023-07-07 18:51:01.380 GRPCLib - Initialize gRPC library
[INFO ] 2023-07-07 18:51:01.380 GRPCLink …
```

feat(uat): implement mqtt5 publish properties for python paho client

---

uat/README.md
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/EventFilter.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEvent.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Add test cases to T102 for 'message expiry interval' feature
- Add steps to set and reset 'message expiry interval' in transmitted and expected received message
- Add step to reset event storage and all MQTT v5.0 settings
- Add test cases to test 'message expiry interval' feature of EMQX
- Add messageExpiryInterval to EventFilter and implementation
- Reoder steps code to be in the same order as in MQTT v5.0 spec to avoid mess
- Update uat/README.md to use @SkipOnWindows
These test cases testing 'message expiry interval' MQTT v5.0 feature
By submitting this pull request, I confirm that you can use, …

feat(uat): add test cases for message expiry interval

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

add responseTopic, correlationData and fix connection port for Java-Paho-client
- add responseTopic and correlationData for Java-Paho-client
- fix setting connection port and schema for Java-Paho-client
to implement Mqtt 5.0 features
**Client's log:**
```
[INFO ] 2023-07-10 18:38:39.707 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as best-thing-akezhan...
[INFO ] 2023-07-10 18:38:40.390 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-07-10 18:38:40.420 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:41799
[INFO ] …
```

feat(uat): add responseTopic, correlationData and fix connection port

---

uat/README.md

PUBREC/PUBREL/PUBCOMP and support for QoS2
Discovery failed on code build
- Update README.md of uat by adding "Limitations" section
- Update README.md of uat by adding  "Run scenarios on CodeBuild" section
We can't implement some MQTT v5.0 features and should note about that.
Documentation update, will review by QA

docs(uat): update uat/README.md

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/addon/EventFilter.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/addon/MqttMessageEvent.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Add test cases to T102 for request/response features
- Add steps to set/reset clean session, keep alive, request response information, response topic tx/rx, correlation data tx/rx
- Add test cases for reponse topic, correlation data and request response information to T102 scenario outline
- Add response topic and correlation data to EventFilter
- Fix unhandled exception and tune logging in paho java client
Automatically test steps, clients and local broker with some new MQTT v5.0 features
Automatically run scenarios on CodeBuild 
```
[INFO ] 2023-07-12 19:51:25.453 [main] StepTrackingReporting - Passed: 'GGMQ-1-T102-v5-sdk-java: As a customer, I can …
```

feat(uat): add test cases to T102 for request/response features

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/AgentTestScenario.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/ExampleControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/EngineControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/mqtt-client-control/src/test/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImplTest.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Test scenarios finish with warning "MqttControlSteps - io.grpc.StatusRuntimeException: UNAVAILABLE: io exception"
gRPC channels are leaked in control
- Make sending  shutdown and close MQTT connections optional
- Resolve issue when send requests to dead agent and closing resources is bypassed
- Resolve channel leak issue when agent is restarted
- Fix mistype in T102
- Add logging about closing resources
Should fix issues related to closing control's resources
Automatically on CodeBuild
Manually on dev host
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …

fix(uat): resolve stop agent and channel leak issues

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

added t20 scenario and added new connection step
- Add T20 scenario 
- Add new failed connection step
to implement Mqtt 5.0 features
```
And I create client device "clientDeviceTest"...............................passed
When I associate "clientDeviceTest" with ggc................................passed
And I update my Greengrass deployment configuration, setting the component …
```

feat(uat): add T20 scenario and new connection step

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

add callback for disconnect
- Add callback for disconnect
- Add properties for disconnect
- Refactor message arriving for listener
Implement callback
Start a local broker and disconnect while the client is running.
```
[INFO ] 2023-07-17 13:45:48.427 [grpc-default-executor-0] GRPCDiscoveryServer - RegisterAgent: agentId client1
[INFO ] 2023-07-17 13:45:48.514 [grpc-default-executor-0] GRPCDiscoveryServer - DiscoveryClient: agentId client1 address 127.0.0.1 port 42735
[INFO ] 2023-07-17 13:45:48.516 [grpc-default-executor-0] EngineControlImpl - Created new agent control for client1 on 127.0.0.1:42735
[INFO ] 2023-07-17 13:45:48.541 …
```

fix(uat): add callback for disconnect

---

uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

- Add T24 scenario
Implement scenarios
Run scenario locally
```
And I update my Greengrass deployment configuration, setting the component aws.greengrass.clientdevices.Auth configuration to:.passed
And I update my Greengrass deployment configuration, setting the component …
```

feat(uat): implement ggmq scenario based on GGAD-1-T24

---

uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt311/client/sdkmqtt/Mqtt311ConnectionImplTest.java
uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImplTest.java

Different behaviors between mqtt3 and mqtt5 when shutting down closed connection
- Bypass calling disconnect() on library client when connection is not connected
- Log warning "DISCONNECT was not sent on the dead connection" instead of disconnect() in such cases
- Update unit tests to move objects to 'connected' state
- Fix error when waiting for closed but close() is not called yet
SDK MQTT v3 client throw an exception while try to call disconnect() on connection dropped by broker.
The same time SDK MQTT v5 client pass as usual.
To avoid control confuse we need to unify client behavior despite of MQTT version.
Manually by terminate local mosquitto broker after client …

fix(uat): bypass send DISCONNECT on dead connection in SDK client

---

uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature
uat/testing-features/src/main/resources/local-store/recipes/client_python_paho.yaml

Implement Windows Build for Python Paho client.
Implement the ability to run test scenarios on Windows for Python Paho Client.
Fix "Response topic and correlation data are received as warnings on python-paho client side" bug.
- Update Python Paho client building system to make it possible running scenarios on Windows
- Response topic and correlation data bug was fixed
Test all scenarios with Python Paho client on Windows
Run scenarios locally on Windows
```
[INFO ] 2023-07-24 19:40:52.140 [main] StepTrackingReporting - Passed: 'GGMQ-1-T1-v3-paho-python: As a customer, I can connect, subscribe/publish at QoS 0 and 1 and receive using client application …
```

feat(uat): add windows build for python paho client

---

uat/README.md
uat/pom.xml
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

add and remove steps for loopback address
- Add 'I add IP address "ip_address" to loopback interface' step
- Add 'I remove IP address "ip_address" from loopback interface' step
- Add plugin to generate html-documentation from JavaDoc
Implement scenarios
Run scenario on CodeBuild
```
And I create client device "basic_connect"..................................passed
When I associate "basic_connect" with …
```

feat(uat): add t21 and plugin to generate html-documentation

---

uat/custom-components/client-python-paho/src/main.py
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_lib.py

Fix "Paho Python Client cannot connect on Windows" bug.
- "Paho Python Client cannot connect on Windows" bug was fixed
- Start connection id was changed from 0 to 1 in Paho Python Client to be consistent with the other clients
Bug is present on Windows for Python version >= 3.8
Run T1 scenario locally on Windows to make sure that the client successfully connect to broker and pass the test
```
[INFO ] 2023-07-27 11:59:55.391 [main] feature - Finished step: 'I create a Greengrass deployment with components' with status PASSED
[INFO ] 2023-07-27 11:59:56.545 [main] EngineControlImpl - MQTT client control gRPC server started, listening on 53256
[INFO ] …
```

feat(uat): fix connect bug on windows for python paho client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

fix error processing in paho-java-client
- change error processing
- add isClosing boolean for callback
Implement scenarios
Start the local broker and shutdown the broker after a successful connection.
```
[INFO ] 2023-07-27 21:08:36.788 [main] GRPCLinkImpl - Making gPRC client connection with 127.0.0.1:47619 as client1...
[INFO ] 2023-07-27 21:08:37.244 [main] GRPCLinkImpl - Client connection with Control is established, local address is 127.0.0.1
[INFO ] 2023-07-27 21:08:37.264 [main] GRPCControlServer - GRPCControlServer created and listed on 127.0.0.1:35873
[INFO ] 2023-07-27 21:08:37.336 [main] GRPCLinkImpl - Handle gRPC requests
[INFO ] …
```

fix(uat): change error processing in paho-java-client

---

uat/README.md
uat/custom-components/client-mosquitto-c/src/MqttConnection.cpp
uat/custom-components/client-mosquitto-c/src/MqttConnection.h

MQTT Client Control does not send shutdown agent request
- Add connection state check before publish, subscribe, unsubscribe, shutdown
- Add shutdown initiated check before shutdown
- Joined with REAME update
Currently mosquitto client throw an exception when closeMqttConnection gRPC request is called on connection already closed from broker's side.
Also behavior of gRPC requests for publish,subscribe,unsubscribe and shutdown when connection is closed by broker depends on mosquitto library which differ from other client. We need unify behavior of clients to simplify control and MQTT steps.
Manually by run Control as application and local mosquitto broker.
When client is …

fix(uat): add connection state check to mosquitto client

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/util/SslUtil.java
uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java

TLS connection fails
- Rework SslUtils to support PCKS#8 key format
- Use list of certificate instead of concatenated to String
- Use certificate presense as mark TLS credentials are present.
Paho-jave client does not support PKCS#8 format of key file.
Manually by run Control as application with key file in PKCS#8 format and for local mosquitto client.
Control
```
$ ./run_for_mosquitto_pkcs8.sh
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int, …
```

fix(uat): resolve issue when key file in PCKS#8 format can't be read

---

uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt311/client/paho/Mqtt311ConnectionImpl.java
uat/custom-components/client-java-paho/src/main/java/com/aws/greengrass/testing/mqtt5/client/paho/MqttConnectionImpl.java

Paho Java - exception when publishing during disconnect
- Switch from file to in-memory persistence module in paho-java
Seems in-file persistence module of paho-java library has a bug and throws an exception when we created second connection with the same MQTT client_id.
Manually by run modified Control app where second connection is established.
For MQTT v5.0:
Control:
```
[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ aws-greengrass-testing-mqtt-client-control ---
[INFO ] 2023-08-01 15:25:42.880 [com.aws.greengrass.testing.mqtt.client.control.ExampleControl.main()] ExampleControl - Control: port 47619, with TLS, MQTT v5
[INFO ] 2023-08-01 …
```

fix(uat): switch from in-files to in-memory persistence module in paho-java

---

uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Implement GGMQ scenario based on GGAD-1-T25
- Add T25 scenario
- Add new step - rename a connection
Implement scenarios
Run scenario locally
```
And I update my Greengrass deployment configuration, setting the component …
```

feat(uat): implement GGMQ scenario based on GGAD-1-T25

---

uat/custom-components/client-python-paho/scripts/build.bat
uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py

MQTT Client Control does not send shutdown agent request
Windows build: script does not fail in case of error
- Add connection state check before publish, subscribe, unsubscribe, shutdown
- Add shutdown initiated check before shutdown
- Add errors handling for Windows build script - fail in case of error
Currently paho python client throws an exception when closeMqttConnection gRPC request is called on connection already closed from broker's side.
We need unify behavior of clients to simplify control and MQTT steps.
Currently Windows build script does not fail in case of error, it can be confusing.
Manually by run Control as application and local mosquitto broker.
When …

feat(uat): add connection state check to Paho Python client

---

uat/codebuild/uat_linux_buildspec.yaml

ip command does not found on Code Build with Ubuntu 20.04
- Install iproute2 package for ip command
- Remove pipeline due to hide tests exist status 
Due to ip command does not installed on Code Build box T21 and T26 were failed.
Because pipeline was used to run test command exist code was lost.
Automatically by run tests on Code Build.

fix(uat): install iproute2 package for ip command; remove commands pipeline

---

uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/AgentControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/api/ConnectionControl.java
uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/AgentControlImpl.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

Use new "CURRENT" version feature of OTF in scenarios
Joined with javadoc comment updates
- Replace LATEST to CURRENT version of client in second deployment of T2 and T13 scenarios
- Tune scenario formatting
- Update javadoc comments to resolve generation issues
Switch to new OTF "CURRENT" version feature
Automatically on Linux via github CI + CodeBuild.
Manually on Windows.

fix(uat): use CURRENT for classpath component in second deployments

---

uat/mqtt-client-control/src/main/java/com/aws/greengrass/testing/mqtt/client/control/implementation/EngineControlImpl.java
uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java

Ease the race between MQTT connection and re-connection of agent
- Move stop old agent control after linking new
- Move getting agent control to as late as possible
When MQTT client component is restarted for example during second deployment it obtain new gRPC control port and re-connecting to control. Engine control creates new agent control instance and update internal map of agents. We have race between that process coming from lower layers (gRPC connection) and scenario step creates MQTT connection for that client. 
When the step wins the race it try to create MQTT connection on dead agent control.
We can't resolve the race completely without explicit synchronization for example waiting until …

fix(uat): ease race between MQTT connect and agent reconnect

---

uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature

UNDEFINED step in T102 scenario
- Correct a mistype in step sentence in T102
Without that change T102 silently failed
Automatically on github CI.
Requires manual check for lines ends with 'with status UNDEFINED' in console output of tests due to probably bug in cucumber: even when undefined step is found whole scenario has PASSED status. The same time status of test correctly appeared in exit code of test command.
Unfortunately 'deployment failed' bug hide actual result of the test command.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

fix(uat): resolve undefined step issue in T102

---

src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificatesConfig.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/CertificatesConfigTest.java

Same as https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/61, with a modification lowering the minimum validity seconds value to 1 minute.  The reason for this is to allow UATs to test rotation within a reasonable period.

feat: re-introduce clientCertificateValiditySeconds config

---

src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificatesConfig.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/CertificatesConfigTest.java

Lower the min value of server cert validity to 1 minute, to allow UATs to test rotation within a reasonable period.

chore: decrease min server cert validity

---

src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java

Refactoring `CISShadowMonitorTest` in advance of https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/405.
* Consolidate all test cases into a single, parameterized test, since the core testing flow is the same
* Move shadow request/response behavior from test cases themselves into `FakeIotShadowClient`
* It will be easier to add upcoming test functionality in future PRs:
* simulating shadow retrieval failures (get request succeeds, but receiving doesn't happen)
* Makes `CISShadowMonitorTest` (subjectively) easier to comprehend and maintain
By submitting this pull request, I …

refactor: cleanup CISShadowMonitorTest

---

src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java

* Add ability for `CISShadowMonitorTest` to simulate shadow get operation failures.
* Add test cases for shadow get failure scenarios
Will be used to validate future PRs when `CISShadowMonitor` becomes resilient to shadow get failures

chore: support shadow rejected in CISShadowMonitorTest

---

src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitor.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/NetworkStateFake.java

On startup, CIS shadow monitor requests the latest CIS shadow via an MQTT request, and will update certificates with host information accordingly.  However, there is a subtle race where nucleus' mqtt client may reset during this CIS shadow get operation (e.g. due to device configuration changing).
This PR adds retry logic when fetching CIS shadows, to ensure we are resilient to failures.  We can simply wait until we receive a get shadow response, which is either:
* get shadow accepted
* get shadow rejected
Accepted is the happy path. We requested a shadow and we received it.  Rejected means the shadow doesn't exist yet; there's no need to retry because we'll get a delta update when the shadow is eventually created.
**Why is this …

fix(cis): retry get shadow operation

---

src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
src/main/java/com/aws/greengrass/clientdevices/auth/exception/CloudServiceInteractionException.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/Certificate.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/CreateIoTThingSession.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyThingAttachedToCertificate.java
src/test/java/com/aws/greengrass/clientdevices/auth/certificate/BackgroundCertificateRefreshTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClientTest.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java

* Have more specific exception messages in `CreateIoTThingSession` to disambiguate failures.
* Make `CloudServiceInteractionException` a checked exception

chore: cleanup exception messaging

---

src/main/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitor.java
src/test/java/com/aws/greengrass/clientdevices/auth/connectivity/CISShadowMonitorTest.java

This PR modifies `CISShadowMonitor` to be resilient to race conditions, such as:
1) receiving shadow delta response around the same time as a get shadow response, during startup up or after network connectivity resumes
2) receiving multiple delta responses in quick succession, due to connectivity shadow being updated quickly
...and the chances increase if the core device is low-powered (takes longer to generate certificates).
Currently, there is no mechanism in place to prevent the interleaving connectivity shadow processing (which includes fetching/updating connectivity info, and generating certificates using such info).  Worst case, this can result in server certificates being generated with old/previous host addresses.
To achieve …

chore(cis): concurrency fixes and cert gen retries

---

generate-parser.sh

Convenience script for generating parser code. 

chore: script to generate parser

---

benchmark/README.md
benchmark/pom.xml
benchmark/run-benchmarks.sh
benchmark/src/main/java/com/aws/greengrass/clientdevices/auth/benchmark/RuleExpressionEvaluationBenchmark.java

Introduce benchmarking to the repo, using JMH (also used in Nucleus repo). For now, added some basic benchmarks for evaluating thingName selection expressions.  Benchmarks can be run using the `run-benchmarks.sh` convenience script.  Future work is to add more benchmarks and have them run in github and report metrics.
So we can get performance numbers on key code paths in CDA, to better inform implementations and allow us to improve over time

feat: add benchmarking

---

.github/workflows/benchmark.yml

Don't run benchmarks when `main` is updated.  Forgot to remove this in https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/416

chore: only run benchmark workflow on prs

---

src/integrationtests/java/com/aws/greengrass/integrationtests/metrics/MetricsEmitterTest.java

Attempt to get rid of null pointers showing up in recent test runs for `GIVEN_kernelRunningWithMetricsConfig_WHEN_verifyClientDeviceIdentity_THEN_successMetricEmitted`

chore: deflake metrics test

---

src/integrationtests/java/com/aws/greengrass/integrationtests/metrics/MetricsEmitterTest.java

Continuation of https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/420, extended to the whole `MetricsEmitterTest`.
Previously we waited for `emitMetrics` to be called to signal a metric was reported, but even with https://github.com/aws-greengrass/aws-greengrass-client-device-auth/pull/420 there is still a race between calling the API and `emitMetrics` (GIVEN_kernelRunningWithMetricsConfig_WHEN_subscribeToCertificateUpdate_THEN_successMetricEmitted, for example was failing unit tests when attempting to make the same change).
To ignore the race, we can capture the first (non empty) list of metrics, and wait for metric emitter to run at least another cycle and verify no extra methods are emitted.  This would …

chore: deflake rest of MetricsEmitterTest

---

src/main/java/com/aws/greengrass/clientdevices/auth/configuration/GroupConfiguration.java
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/PolicyVariableResolver.java
src/test/java/com/aws/greengrass/clientdevices/auth/configuration/GroupConfigurationTest.java

Validate that policy resources only contain expected policy variables. Had to modify the `${}` regex to accept anything in order to detect bad cases.  Also made some changes to support case-insensitive variables (willing to remove if we think we don't need case insensitivity)

chore: validate policy variables

---

src/integrationtests/java/com/aws/greengrass/integrationtests/policy/PolicyTest.java
src/integrationtests/resources/com/aws/greengrass/integrationtests/policy/empty-config.yaml
src/main/java/com/aws/greengrass/clientdevices/auth/configuration/GroupDefinition.java

Adding some more test coverage at the integration level.  Tests that if resource A is removed from a policy, that we immediately are no longer able to publish to it

chore: add integ test for removing resources from policy

---

src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java

Move config subscription and validation from `install` to `startup` stage.
Moving the config validation to the startup stage will prevent CDA from ever reaching the RUNNING state if the config is bad.  

fix: move config validation to startup stage so bad configs will break the component

---

src/integrationtests/java/com/aws/greengrass/integrationtests/policy/PolicyTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java

Validate CDA config during startup and force CDA to error if a validation exception is thrown.
Without this change, CDA will not reach the broken state when there is a bad config.
Integration testing

fix: validate config and error service during startup

---

src/main/java/com/aws/greengrass/clientdevices/auth/certificate/handlers/CAConfigurationChangedHandler.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureCustomCertificateAuthority.java
src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureManagedCertificateAuthority.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/CreateIoTThingSession.java
src/main/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactory.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java

MQTT client IDs are at most 65,535 by the current MQTT 5 specification. Add a limit to our code if the MQTT broker itself does not do the validation.
Added a test

fix: limit client IDs to 65,535

---

src/main/java/com/aws/greengrass/clientdevices/auth/iot/Thing.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/CreateIoTThingSession.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java

Limit thing names to 128 characters to fail fast for invalid names.

fix: limit thing name to 128 characters

---

src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/BackgroundRefreshTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/infra/ThingRegistry.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/CreateIoTThingSession.java
src/test/java/com/aws/greengrass/clientdevices/auth/session/MqttSessionFactoryTest.java

`getOrCreateThing` writes to our config which is necessary to perform the validation, but if validation failed and the thing hasn't been seen before, then we make sure to delete the thing from our config.

fix: delete thing from local registry if validation fails

---

benchmark/pom.xml
pom.xml
src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
src/main/java/com/aws/greengrass/clientdevices/auth/iot/GreengrassV2DataClientFactory.java

1. Updating the dependencies
2. Update method to provide ggv2dataclient endpoint
3. Ignoring device offline exceptions in unit testing since we're targeting authentication and the device offline related exceptions are expected
It's used to support fips feature where the endpoint should be override earlier than built-in useFips function
With UAT

chore(fips): update endpoint overwrite method
