- src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitor.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/CISShadowMonitorTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitorTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateHelperTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateRequestGeneratorTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateStoreTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/ClientCertificateGeneratorTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/ServerCertificateGeneratorTest.java
- src/test/java/com/aws/greengrass/util/ParseIPAddressTest.java
Remove overly complicated Queue which wasn't adding any value.
> refactor: simplify CertificateExpiryMonitor to remove queue

- .github/workflows/maven.yml
**Description of changes:** Adds Windows build to GH workflow
**How was this change tested:** `mvn -ntp -U clean verify` on Windows
> chore: add Windows build to GH workflow

- src/test/java/com/aws/greengrass/certificatemanager/certificate/CertificateExpiryMonitorTest.java
Check cert rotation for MAX_SERVER_CERT_EXPIRY. It should not rotate cert at DEFAULT_SERVER_CERT_EXPIRY
Adds a test
`mvn clean verify`
> test: add test to check cert rotation for MAX_SERVER_CERT_EXPIRY

- src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificateGenerator.java
- src/main/java/com/aws/greengrass/certificatemanager/certificate/CertificatesConfig.java
- src/main/java/com/aws/greengrass/certificatemanager/certificate/ClientCertificateGenerator.java
- src/main/java/com/aws/greengrass/certificatemanager/certificate/ServerCertificateGenerator.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/ClientCertificateGeneratorTest.java
- src/test/java/com/aws/greengrass/certificatemanager/certificate/ServerCertificateGeneratorTest.java
Adds a configuration to disable certificate rotations. 
To provide an emergency mechanism to stop certificate rotations.
Unit tests
> feat: config to disable certificate rotation

- src/main/java/com/aws/greengrass/device/DeviceAuthClient.java
> fix: early exit on empty cert path

- pom.xml
> chore: bump version to 2.3

- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CISShadowMonitor.java
- src/test/java/com/aws/greengrass/clientdevices/auth/certificate/CISShadowMonitorTest.java
Issue #, if available:
Description of changes:
This change modifies CISShadowMonitor so that it rotates certificates when it detects a change in the CIS shadow `version` field, rather than a change in shadow _document_ version.
Why is this change necessary:
This fixes an issue where certificates are rotated unnecessarily when a recconect occurs (when we process a CIS shadow, we publish reported state to it, bumping the shadow document version. if a recconect occurs in the future, certs will be rotated even if connectivity info hasn't changed, because CISShadowMonitor only cared that the shadow version changed)
How was this change tested:
Tested by blocking MQTT traffic (to force a disconnect), then unblocking it to force a shadow fetch. Ensured that the shadow was not reprocessed.
``` …
```
> fix: rotate certs when change in cis shadow version field

- recipe.json
> chore: support Nucleus 2.7

- src/main/java/com/aws/greengrass/clientdevices/auth/CertificateManager.java
- src/main/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthService.java
- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java
- src/main/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfiguration.java
- src/test/java/com/aws/greengrass/clientdevices/auth/CertificateManagerTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/ClientDevicesAuthServiceTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/configuration/CAConfigurationTest.java
- src/test/resources/com/aws/greengrass/clientdevices/auth/config_with_ec_ca.yaml
- Model  the CA config of CDA config and also include BYO CA keys. 
- Pass the CAConfiguration object to cert manager
- Needed to support BYOCA feature. 
- Refactoring code
> refactor: update CDA configuration

- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/listeners/CACertificateChainChangedListener.java
- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/usecases/ConfigureCertificateAuthorityUseCase.java
> fix: use cases is no longer a singleton

- src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java
Remove additional retries from the IoT auth client since the default data client already has a built in retry policy.
CDA currently blocks the auth thread for a very long time if GG is in a disconnected state.
> fix: remove retries from IotAuthClient

- src/main/java/com/aws/greengrass/clientdevices/auth/api/ClientDevicesAuthServiceApi.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/Certificate.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/InvalidCertificateException.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClient.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistry.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyIotCertificate.java
- src/test/java/com/aws/greengrass/clientdevices/auth/configuration/GroupDefinitionTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/configuration/GroupManagerTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/iot/IotAuthClientTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/iot/registry/ThingRegistryTest.java
Revision of #145 which removes the registry changes and focuses primarily on Certificate.
Future revisions will flesh out the Registry, as well as add better test support so Registry changes don't break our integ tests (which they currently do).
> feat: add certificate domain logic

- src/main/java/com/aws/greengrass/clientdevices/auth/configuration/RuntimeConfiguration.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/dto/CertificateV1.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/dto/ThingV1.java
- src/test/java/com/aws/greengrass/clientdevices/auth/configuration/RuntimeConfigurationTest.java
> feat: initial runtime configuration storage for iot domain objects

- src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/AuthorizeClientDeviceActionTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/GetClientDeviceAuthTokenTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/SubscribeToCertificateUpdatesTest.java
- src/integrationtests/java/com/aws/greengrass/integrationtests/ipc/VerifyClientDeviceIdentityTest.java
- src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/BrokerNotAuthorized.yaml
- src/integrationtests/resources/com/aws/greengrass/integrationtests/ipc/cda.yaml
> test: fix verify client device identity integ tests

- src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCaConfigurationTest.java
> fix: set iot client to fake

- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStore.java
- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/BackgroundCertificateRefresh.java
- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/ClientCertificateStore.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/CertificateRegistry.java
- src/test/java/com/aws/greengrass/clientdevices/auth/certificate/BackgroundCertificateRefreshTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateStoreTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/certificate/ClientCertificateStoreTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/iot/CertificateRegistryTest.java
> feat: persist client certs

- src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/CustomCATest.java
This PR adds integration tests for changing the configuration from custom ca to managed ca and also tests that custom ca configuration works when the provided ca is not the full chain but just the root ca
> feat: integ test for switching back to managed and using root ca directly

- src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
Technically this is a subset of some of the other offline auth tests, but I'm including it here so it is very obvious what our test coverage is.
> test: basic offline auth integ test

- src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
> test: offline auth with expired ttl

- src/integrationtests/java/com/aws/greengrass/integrationtests/certificateauthority/OfflineAuthenticationTest.java
Test certificate detached from thing, when offline, then when back online authentication fails
> test: certificate detached from thing authentication fails

- recipe.json
> chore: bump nucleus dependency version

- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/infra/BackgroundCertificateRefresh.java
- src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyThingAttachedToCertificate.java
Just changing some log levels here to avoid a few unnecessary chatty logs from being printed
> fix: change log levels

- pom.xml
> chore: bump to version 2.4

- src/main/java/com/aws/greengrass/ipc/SubscribeToCertificateUpdatesOperationHandler.java
> feat: handle IPC requests in CDA to deliver client certs

- pom.xml
- src/main/java/com/aws/greengrass/clientdevices/auth/certificate/CertificateHelper.java
- src/test/java/com/aws/greengrass/clientdevices/auth/certificate/ClientCertificateGeneratorTest.java
- src/test/java/com/aws/greengrass/clientdevices/auth/helpers/CertificateTestHelpers.java
Use bouncycastle's FIPS distribution.
> fix(fips): use bouncycastle fips provider

- uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
- uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
- uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCControlServer.java
- uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCDiscoveryClient.java
- uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
- uat/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImpl.java
- uat/src/main/proto/mqtt_client_control.proto
Implement publish operation in the test MQTT client.
- Added basic publish
- Added timeout of operation to protocol
- Added timeout check on client side
- Added disconnect timeout configuration
MQTT5 client should be able to publish MQTT messages
At the moment manually, later we cover code by unit tests
> Implement publish in MQTT v5.0 test client (uat)

- .github/workflows/uat.yml
Add Windows build for MQTT client.
Added Windows build on CI for uat MQTT test client.
Test client should be available not only on Linux but also on Windows.
tested by CI runs
> ci(uat): added windows build

- pom.xml
> chore: bump to 2.5.0

- uat/custom-components/client-java-sdk/pom.xml
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttConnection.java
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/MqttLib.java
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImpl.java
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImpl.java
- uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttConnectionImplTest.java
- uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/sdkmqtt/MqttLibImplTest.java
Create unit tests of AWS IoT device SDK client
-  added unit tests for MqttConnectionImpl
- added unit tests for MqttLibImpl
MQTT client based on AWS IoT device SDK should be covered by unit tests
Unit tests will run on CI
> test(uat): added unit tests for MqttConnectionImpl and MqttLibImpl

- uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
- added step to associate client device with core device
- required step for client devices functionality
> feat(uat): created device association step

- uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
- uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature
- added device discovery step
- to use in feature testing
`java -Dggc.archive=./greengrass-nucleus-latest.zip -Dtest.log.path=./logs -Dtags=GGMQ -jar uat/testing-features/target/client-devices-auth-testing-features.jar`
**Test result summary:**
```
And I create client device "clientDeviceTest"...............................passed
And I update my Greengrass deployment configuration, setting the component aws.greengrass.clientdevices.Auth configuration …
```
> feat(uat): device discovery step

- uat/testing-features/src/main/java/com/aws/greengrass/steps/MqttControlSteps.java
- uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature
Create validate connection step
Deleted validation step and added step set mqtt timeout in MqttControlSteps
Code of MQTT client based on AWS IoT device SDK should be covered by unit tests.
At the moment manually, as part of test scenario. In phase 2 we are going to cover by unit tests.
> refactor(uat): deleted validation and added step set mqtt timeout in MqttControlSteps

- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/GRPCLib.java
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/Main.java
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImpl.java
- uat/custom-components/client-java-sdk/src/main/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImpl.java
- uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLibImplTest.java
- uat/custom-components/client-java-sdk/src/test/java/com/aws/greengrass/testing/mqtt5/client/grpc/GRPCLinkImplTest.java
- uat/pom.xml
Multi-homed control is not supported
- Replace array of IP addresses to List
PR review requirement.
Unit tests for that logic is also updated.
> refactor(uat): replace array of IP addresses to List

- uat/codebuild/uat_linux_buildspec.yaml
- uat/pom.xml
> chore(deps): use OTF 1.2

- uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature
Implement GGMQ scenario based on GGAD-1-T9 and GGAD-1-T14
- Add GGMQ-1-T9 scenario outline for MQTT v3 and v5 and sdk-java and mosquitto-c clients
Testing ability to forward local MQTT messages to IoT core
Run scenarios locally and on codeBuild.
```
[INFO ] 2023-06-16 19:14:11.608 [main] StepTrackingReporting - Passed: 'GGMQ-1-T9-v3-sdk-java: As a customer,I can configure local MQTT messages to be forwarded to an IoT Core MQTT topic'
[INFO ] 2023-06-16 19:14:11.608 [main] StepTrackingReporting - Passed: 'GGMQ-1-T9-v3-mosquitto-c: As a customer,I can configure local MQTT messages to be forwarded to an IoT Core MQTT topic'
[INFO ] 2023-06-16 19:14:11.608 …
```
> feat(uat): add T9 scenario outline with 2 clients

- uat/README.md
- uat/testing-features/src/main/java/com/aws/greengrass/steps/AssertionSteps.java
[Windows] Greengrass process doesn't stop during running test scenarios
- Update uat/README.md to provide actual and clear instructions to build on Windows
Keep readme actual
Review by QA
> fix(uat): update uat/README.md

- uat/custom-components/client-python-paho/src/grpc_client_server/grpc_control_server.py
- uat/custom-components/client-python-paho/src/mqtt_lib/mqtt_connection.py
- Update Python Paho client to handle PUBLISH Response Topic in Tx and Rx directions
- Update Python Paho client to handle PUBLISH Correlation Data in Tx and Rx directions
- Update Python Paho client to handle CONNECT Request Response Information
(handling response information in CONNACK was implemented earlier)
MQTT connect, subscribe, unsubscribe, publish, delivery of received MQTT message and disconnect are successful. Linking and shutdown steps are successful.
```
[DEBUG] 2023-07-12 17:21:50.751 asyncio - Using …
```
> feat(uat): implement request response features in python paho client

- uat/testing-features/src/main/resources/greengrass/features/ggmq-1.feature
Implement GGMQ scenario based on GGAD-1-T17, GGAD-1-T18
- Disable GGMQ-1-T17 on Windows
- Fix GGMQ-1-T18 to run on Windows
T17 passed but useless on Windows due to Nucleus is not restarted
T18 was expecting message from Bridge but it does not disconnected from EMQX on Windows 
Run T18 scenarios on Windows and Linux
Run T17 scenarios on Linux
> fix(uat): disable T17 on Windows and fix T18

- .github/workflows/maven.yml
Same as https://github.com/aws-greengrass/aws-greengrass-mqtt-bridge/pull/159
> chore: reduce noise in code coverage comment

- src/main/java/com/aws/greengrass/clientdevices/auth/iot/usecases/VerifyIotCertificate.java
Remove stored certificate if validation fails. This would happen automatically on background refresh, but take care of it immediately now.
> fix: remove invalid certificates if validation fails

- .github/workflows/benchmark.yml
- .github/workflows/maven.yml
> ci: upgrade github actions

- benchmark/pom.xml
- pom.xml
> chore: bump to next version
